---

- name: Run django environment
  hosts: django
  become: yes
  pre_tasks:
    - name: Make sure paxctld is started
      service:
        name: paxctld
        state: started
      when: ansible_kernel.endswith('grsec')
  roles:
    - role: freedomofpress.django_stack
      tags: django
  post_tasks:
    - name: Run tests
      script: scripts/django_tests.sh
      tags: tests
      become: yes
      become_user: "{{ django_stack_gcorn_user }}"
      no_log: true
      register: test_run_results
      # Need this to keep going and get us test output xml
      ignore_errors: yes

    - name: Yank out tests for analysis
      fetch:
        src: "/home/gcorn/app-tests.xml"
        dest: ../test-results/
        flat: yes
      tags: tests

    - name: Fail if test failed earlier
      fail:
      when: test_run_results|failed
      tags: tests
  vars:
    django_stack_superuser_admin: admin
    django_stack_superuser_email: mike@freedom.press
    django_db_user: django_user
    django_db_password: django_password
    django_stack_app_name: pressfreedom
    django_secret_key: f1822d2fe58daeadc88e0e4eef2f155fc3edd3713ff9a5d1e27696afd9231d905db51c98dc
    django_stack_es_host_url: disable
    django_stack_deploy_src: "{{ lookup('pipe', 'pwd') }}/../"
    django_stack_manage_post:
      - createdevdata
    django_stack_npm_commands:
      - run build
    django_stack_gunicorn_opt_envs:
      DJANGO_ALLOWED_HOSTS: "'*'"
      DJANGO_SETTINGS_MODULE: pressfreedom.settings.production-ci
      DJANGO_JSON_LOG: True
      DJANGO_DB_NAME: pressfreedom
    django_stack_gcorn_app_settings: pressfreedom.settings.production-ci
    django_stack_force_refresh: true
    django_stack_rsync_opts:
      - "--exclude=.git"
      - "--exclude=devops"
      - "--exclude=node_modules"
      - "--exclude=src"
    # The default packages are preinstalled on the base dockerimage
    django_stack_pkgs: []
