---
- src: https://github.com/freedomofpress/ansible-role-openssl-node.git
  name: freedomofpress.openssl_node

- name: jdauphant.nginx

- name: ANXS.postgresql

- name: geerlingguy.nodejs

- src: https://github.com/freedomofpress/django_stack.git
  name: freedomofpress.django_stack
  version: 10acb7a7f81f831535ffe610d66b357eff1282dd
