---

- name: Run django environment
  hosts: django
  become: yes
  pre_tasks:
    - name: Make sure paxctld is started
      service:
        name: paxctld
        state: started
      when: ansible_kernel.endswith('grsec')
  roles:
    - role: freedomofpress.django
      tags: django
  vars:
    django_stack_superuser_admin: admin
    django_stack_superuser_email: mike@freedom.press
    django_db_user: django_user
    django_db_password: django_password
    django_stack_app_name: tracker
    django_secret_key: f1822d2fe58daeadc88e0e4eef2f155fc3edd3713ff9a5d1e27696afd9231d905db51c98dc
    django_stack_es_host_url: disable
    django_stack_deploy_src: "{{ lookup('pipe', 'pwd') }}/../../"
    django_stack_db_tasks:
      - migrate
      - collectstatic
      - createdevdata
    django_stack_npm_install_cmd: "npm install; npm run build"
    django_stack_gunicorn_opt_envs:
      DJANGO_ALLOWED_HOSTS: "'*'"
      DJANGO_SETTINGS_MODULE: tracker.settings.production-ci
      DJANGO_JSON_LOG: True
      DJANGO_DB_NAME: pressfreedom
    django_stack_gcorn_app_settings: tracker.settings.production-ci
    django_stack_node_ver: 10.15.1-alpine
    django_stack_force_refresh: true
    django_stack_rsync_opts:
      - "--exclude=devops"
      - "--exclude=node_modules"
      - "--exclude=src"
    # The default packages are preinstalled on the base dockerimage
    django_stack_pkgs: []
    django_stack_global_no_log: yes
    django_stack_manage_no_log: no
