---
- name: Run django tests
  hosts: all
  tasks:
    - name: Run tests
      script: django_tests.sh
      become: yes
      become_user: "gcorn"
      no_log: true
      register: test_run_results
      # Need this to keep going and get us test output xml
      ignore_errors: yes

    - name: Yank out tests for analysis
      fetch:
        src: "/home/gcorn/app-tests.xml"
        dest: ../../test-results/
        flat: yes

    - name: Fail if test failed earlier
      fail:
      when: test_run_results is failed
