# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='button_text',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
