# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0025_socialsharingseosettings'),
        ('forms', '0002_formpage_button_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='search_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.CustomImage'),
        ),
    ]
