# Generated by Django 2.2.14 on 2020-08-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20190318_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='use_as_reply_to',
            field=models.BooleanField(default=False, help_text='Use the contents of this field as the Reply-To header of the email sent by this from.  Only one field per form can have this checked.'),
        ),
        migrations.AddConstraint(
            model_name='formfield',
            constraint=models.UniqueConstraint(condition=models.Q(use_as_reply_to=True), fields=('page',), name='only_one_reply_to_form_field'),
        ),
    ]
