# Generated by Django 2.2.14 on 2020-08-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_auto_20200812_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='append_to_subject',
            field=models.BooleanField(default=False, help_text='Add the contents of this field to the subject of the email sent by this from.  All fields with this checked will be appended.'),
        ),
    ]
