# Generated by Django 3.2.12 on 2022-03-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_auto_20220222_0331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldgroup',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterField(
            model_name='fieldgroup',
            name='template',
            field=models.CharField(choices=[('default', 'Default'), ('date_single', 'Single date')], default='default', help_text='Select template used to display this field group', max_length=20),
        ),
    ]
