# Generated by Django 4.2.27 on 2025-12-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_auto_20221110_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='honeypot',
            field=models.BooleanField(default=False, verbose_name='Honeypot Enabled'),
        ),
    ]
