# Generated by Django 5.2.13 on 2026-05-06 19:57

from django.db import migrations, models

import wagtail_honeypot.models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0012_formpage_honeypot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formpage",
            name="honeypot",
            field=models.BooleanField(
                default=wagtail_honeypot.models.get_honeypot_default,
                verbose_name="Honeypot enabled",
            ),
        ),
    ]
