files:
    include:
        - '**/*.s+(a|c)ss'
    ignore:
        - 'node_modules/**/*'

rules:
    indentation:
        - 2
        - size: 'tab'
    property-sort-order: 0
    no-color-keywords: 0
    leading-zero:
        - 2
        - include: true
    class-name-format:
        - 2
        - convention: hyphenatedbem
    force-pseudo-nesting: 0
    force-element-nesting: 0
    shorthand-values:
        - 2
        - allowed-shorthands:
            - 1
            - 2
    single-line-per-selector: 2
