files:
    include:
        - '**/*.s+(a|c)ss'
    ignore:
        - 'node_modules/**/*'

rules:
    indentation:
        - 2
        - size: 'tab'
    property-sort-order: 0
    no-color-keywords: 0
    leading-zero:
        - 2
        - include: true
    class-name-format:
        - 2
        - convention: hyphenatedbem
