extends:
    - stylelint-config-standard
    - stylelint-config-recommended
    - stylelint-config-sass-guidelines
customSyntax: postcss-sass
ignoreFiles:
  - 'node_modules/**/*'
files:
    include:
        - '**/*.s+(a|c)ss'
rules:
    indentation: null
    value-keyword-case: [
        lower, {
            ignoreKeywords: ['currentColor']
        }
    ]
    selector-max-compound-selectors: null
    block-closing-brace-empty-line-before: null
    block-closing-brace-newline-after: null
    block-closing-brace-newline-before: null
    block-closing-brace-space-before: null
    block-opening-brace-newline-after: null
    block-opening-brace-space-after: null
    block-opening-brace-space-before: null
    declaration-block-semicolon-newline-after: null
    declaration-block-semicolon-space-after: null
    declaration-block-semicolon-space-before: null
    declaration-block-trailing-semicolon: null
    declaration-block-no-redundant-longhand-properties: null
    max-line-length: null
    max-nesting-depth: null
    selector-list-comma-newline-after: null
    selector-no-qualifying-type: null
    selector-class-pattern: null
    rule-empty-line-before: null
    color-function-notation: legacy
    alpha-value-notation: number
