extends:
    - stylelint-config-standard
    - stylelint-config-recommended
    - stylelint-config-sass-guidelines
customSyntax: postcss-sass
files:
    include:
        - '**/*.s+(a|c)ss'
    ignore:
        - 'node_modules/**/*'
rules:
    indentation: tab
    block-closing-brace-empty-line-before: null
    block-closing-brace-newline-after: null
    block-closing-brace-newline-before: null
    block-closing-brace-space-before: null
    block-opening-brace-newline-after: null
    block-opening-brace-space-after: null
    block-opening-brace-space-before: null
    declaration-block-semicolon-newline-after: null
    declaration-block-semicolon-space-after: null
    declaration-block-semicolon-space-before: null
    declaration-block-trailing-semicolon: null
    order/properties-alphabetical-order: null
    max-nesting-depth: null
    selector-list-comma-newline-after: null
    selector-no-qualifying-type: null
    color-function-notation: legacy
    alpha-value-notation: number
    color-hex-case: upper
