---
version: "3"
networks:
  app:
services:
  postgresql:
    image: postgres:9.5
    ports:
      - "127.0.0.1::5432"
    volumes:
      - ./:/django:ro
    environment:
      POSTGRES_PASSWORD: trackerpassword
      POSTGRES_USER: tracker
      POSTGRES_DB: trackerdb
    user: postgres
    networks:
      app:
        aliases:
          - db

  node:
    build:
      context: .
      dockerfile: devops/docker/NodeDockerfile
      args:
        NODE_VER: 10.17.0-alpine
        NPM_VER: 6.13.4
        USERID: ${UID:?err}
    volumes:
      - ./:/django
    working_dir: /django
    user: ${UID:?err}
    networks:
      - app

  django:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: devops/docker/DevDjangoDockerfile
      args:
        USERID: ${UID:?err}
        PYTHON_VER: 3.7-slim
    depends_on:
      - node
      - postgresql
    environment:
      DJANGO_CREATEDEVDATA: "${DJANGO_CREATEDEVDATA:-no}"
      DJANGO_DB_PASSWORD: trackerpassword
      DJANGO_DB_USER: tracker
      DJANGO_DB_NAME: trackerdb
      DJANGO_DB_PORT: 5432
      DJANGO_DB_HOST: db
      DJANGO_XMLTEST_OUTPUT: "yes"
      DEPLOY_ENV: dev
    working_dir: /django
    volumes:
      - ./:/django
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      app:
        aliases:
          - app
