---
version: "3.4"
networks:
  app:

x-chart-pregenerator:
  host: &chart-host ${NODE_CHART_PREGENERATOR_HOST:-chartgenerator}
  port: &chart-port ${NODE_CHART_PREGENERATOR_PORT:-3000}

services:
  postgresql:
    image: postgres:13
    init: true
    ports:
      - "5432:5432"
    volumes:
      - ./:/django:ro
    environment:
      POSTGRES_PASSWORD: trackerpassword
      POSTGRES_USER: tracker
      POSTGRES_DB: trackerdb
    user: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-U", "tracker", "--dbname", "trackerdb"]
      timeout: 45s
      interval: 10s
      retries: 10
    networks:
      app:
        aliases:
          - db

  selenium:
    image: selenium/standalone-firefox-debug:latest
    ports:
      - "127.0.0.1::5900"
    networks:
      app:
        aliases:
          - selenium

  node:
    init: true
    build:
      context: .
      dockerfile: devops/docker/NodeDockerfile
      args:
        NPM_VER: 9.6.7
        USERID: ${UID:?err}
    volumes:
      - ./:/django
    working_dir: /django
    user: ${UID:?err}
    healthcheck:
      test: jq '.status' webpack-stats.json |grep -q -e compiling -e error -e done
      interval: 10s
      start_period: 1m30s
    networks:
      - app

  node-chart-pregenerator:
    init: true
    build:
      context: .
      dockerfile: devops/docker/NodeChartPregeneratorDockerfile
      args:
        NPM_VER: 9.6.7
        USERID: ${UID:?err}
    volumes:
      - ./:/django
    environment:
      DJANGO_HOST: app
      PORT: *chart-port
      DEPLOY_ENV: dev
    ports:
      - target: *chart-port
        published: *chart-port
    working_dir: /django/chart_pregenerator
    user: ${UID:?err}
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3000/"]
      start_period: 10s
      interval: 30s
      timeout: 20s
      retries: 4
    networks:
      app:
        aliases:
          - *chart-host

  django:
    init: true
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: devops/docker/DevDjangoDockerfile
      args:
        USERID: ${UID:?err}
    depends_on:
      node:
        condition: service_healthy
      postgresql:
        condition: service_healthy
      node-chart-pregenerator:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/health/ok/?monitor"]
      start_period: 10s
      interval: 30s
      timeout: 20s
      retries: 4
    environment:
      DJANGO_ALLOWED_HOSTS: app localhost
      DJANGO_CREATEDEVDATA: "${DJANGO_CREATEDEVDATA:-no}"
      DJANGO_DB_PASSWORD: trackerpassword
      DJANGO_DB_USER: tracker
      DJANGO_DB_NAME: trackerdb
      DJANGO_DB_PORT: 5432
      DJANGO_DB_HOST: db
      DJANGO_XMLTEST_OUTPUT: "yes"
      DEPLOY_ENV: dev
      DJANGO_PROFILE: "${DJANGO_PROFILE:-no}"
      PYINSTRUMENT: "${PYINSTRUMENT:-no}"
      SELENIUM_HOST: selenium
      DJANGO_CHART_HOST: node-chart-pregenerator
      DJANGO_CHART_PORT: *chart-port
    working_dir: /django
    volumes:
      - ./:/django
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      app:
        aliases:
          - app
