CIRCUITS = {
    'Alabama': 'eleventh',
    'Alaska': 'ninth',
    'Arizona': 'ninth',
    'Arkansas': 'eighth',
    'California': 'ninth',
    'Colorado': 'tenth',
    'Connecticut': 'second',
    'Delaware': 'third',
    'District of Columbia': 'district_of_columbia',
    'Florida': 'eleventh',
    'Georgia': 'eleventh',
    'Hawaii': 'ninth',
    'Idaho': 'ninth',
    'Illinois': 'seventh',
    'Indiana': 'seventh',
    'Iowa': 'eighth',
    'Kansas': 'tenth',
    'Kentucky': 'sixth',
    'Louisiana': 'fifth',
    'Maine': 'first',
    'Maryland': 'fourth',
    'Massachusetts': 'first',
    'Michigan': 'sixth',
    'Minnesota': 'eighth',
    'Mississippi': 'fifth',
    'Missouri': 'eighth',
    'Montana': 'ninth',
    'Nebraska': 'eighth',
    'Nevada': 'ninth',
    'New Hampshire': 'first',
    'New Jersey': 'third',
    'New Mexico': 'tenth',
    'New York': 'second',
    'North Carolina': 'fourth',
    'North Dakota': 'eighth',
    'Ohio': 'sixth',
    'Oklahoma': 'tenth',
    'Oregon': 'ninth',
    'Pennsylvania': 'third',
    'Puerto Rico': 'first',
    'Rhode Island': 'first',
    'South Carolina': 'fourth',
    'South Dakota': 'eighth',
    'Tennessee': 'sixth',
    'Texas': 'fifth',
    'Utah': 'tenth',
    'Vermont': 'second',
    'Virginia': 'fourth',
    'Washington': 'ninth',
    'West Virginia': 'fourth',
    'Wisconsin': 'seventh',
    'Wyoming': 'tenth',
}
