CIRCUITS_BY_STATE = {
    'Alabama': 'eleventh',
    'Alaska': 'ninth',
    'Arizona': 'ninth',
    'Arkansas': 'eighth',
    'California': 'ninth',
    'Colorado': 'tenth',
    'Connecticut': 'second',
    'Delaware': 'third',
    'District of Columbia': 'district_of_columbia',
    'Florida': 'eleventh',
    'Georgia': 'eleventh',
    'Hawaii': 'ninth',
    'Idaho': 'ninth',
    'Illinois': 'seventh',
    'Indiana': 'seventh',
    'Iowa': 'eighth',
    'Kansas': 'tenth',
    'Kentucky': 'sixth',
    'Louisiana': 'fifth',
    'Maine': 'first',
    'Maryland': 'fourth',
    'Massachusetts': 'first',
    'Michigan': 'sixth',
    'Minnesota': 'eighth',
    'Mississippi': 'fifth',
    'Missouri': 'eighth',
    'Montana': 'ninth',
    'Nebraska': 'eighth',
    'Nevada': 'ninth',
    'New Hampshire': 'first',
    'New Jersey': 'third',
    'New Mexico': 'tenth',
    'New York': 'second',
    'North Carolina': 'fourth',
    'North Dakota': 'eighth',
    'Ohio': 'sixth',
    'Oklahoma': 'tenth',
    'Oregon': 'ninth',
    'Pennsylvania': 'third',
    'Puerto Rico': 'first',
    'Rhode Island': 'first',
    'South Carolina': 'fourth',
    'South Dakota': 'eighth',
    'Tennessee': 'sixth',
    'Texas': 'fifth',
    'Utah': 'tenth',
    'Vermont': 'second',
    'Virginia': 'fourth',
    'Washington': 'ninth',
    'West Virginia': 'fourth',
    'Wisconsin': 'seventh',
    'Wyoming': 'tenth',
}

STATES_BY_CIRCUIT = {
    'first': [
        'Maine',
        'Massachusetts',
        'New Hampshire',
        'Rhode Island',
        'Puerto Rico',

    ],
    'second': [
        'Connecticut',
        'New York',
        'Vermont',
    ],
    'third': [
        'Delaware',
        'New Jersey',
        'Pennsylvania',
    ],
    'fourth': [
        'Maryland',
        'North Carolina',
        'South Carolina',
        'Virginia',
        'West Virginia',

    ],
    'fifth': [
        'Louisiana',
        'Mississippi',
        'Texas',
    ],
    'sixth': [
        'Kentucky',
        'Michigan',
        'Ohio',
        'Tennessee',
    ],
    'seventh': [
        'Illinois',
        'Indiana',
        'Wisconsin'
    ],
    'eighth': [
        'Arkansas',
        'Iowa',
        'Minnesota',
        'Missouri',
        'Nebraska',
        'North Dakota',
        'South Dakota',
    ],
    'ninth': [
        'Alaska',
        'Arizona',
        'California',
        'Hawaii',
        'Idaho',
        'Montana',
        'Nevada',
        'Oregon',
        'Washington',
    ],
    'tenth': [
        'Colorado',
        'Kansas',
        'New Mexico',
        'Oklahoma',
        'Utah',
        'Wyoming'
    ],
    'eleventh': [
        'Alabama', 'Florida', 'Georgia'
    ],
    'district_of_columbia': [
        'District of Columbia'
    ]
}
