# Generated by Django 2.2.24 on 2021-09-14 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geonames', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='isocode',
            field=models.ForeignKey(db_column='isocode', on_delete=django.db.models.deletion.PROTECT, to='geonames.Country'),
        ),
    ]
