# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_footersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorypage',
            name='plural_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
