# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-12 17:51
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_simplepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypage',
            name='description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categorypage',
            name='methodology',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categorypage',
            name='retrospective_info',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
    ]
