# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-28 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20170412_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('body', wagtail.wagtailcore.fields.RichTextField()),
                ('link_url', models.URLField(blank=True, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_facts', to='common.CategoryPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
