# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_change_to_custom_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
