# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-03 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_simplepagewithsidebar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='category',
        ),
    ]
