# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_add_common_tag'),
        ('incident', '0009_change_tags_to_m2ms'),
    ]

    operations = [
        migrations.DeleteModel('Tag'),
    ]
