# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_remove_tag_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorypage',
            name='retrospective_info',
        ),
    ]
