# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_add_custom_embed_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorypage',
            name='description',
        ),
    ]
