# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 23:14
from __future__ import unicode_literals

from django.db import connection, migrations


def forward(apps, schema_editor):
    CustomImage = apps.get_model('common.CustomImage')
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM pg_get_serial_sequence(%s, 'id')", (CustomImage._meta.db_table,))
        sequence_name = cursor.fetchone()[0]
        cursor.execute("SELECT nextval(%s)", (sequence_name,))
        new_value = cursor.fetchone()[0]
        cursor.execute("ALTER SEQUENCE {} RESTART WITH %s".format(sequence_name), (new_value,))


def reverse(*args):
    # Intentional no-op
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_remove_categorypage_description'),
    ]

    operations = [
        migrations.RunPython(forward, reverse)
    ]
