# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 23:14
from __future__ import unicode_literals

from django.db import migrations


def forward(apps, schema_editor):
    # There was a migration here, it is superseded by 0014.
    pass


def reverse(*args):
    # Intentional no-op
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_remove_categorypage_description'),
    ]

    operations = [
        migrations.RunPython(forward, reverse, elidable=True)
    ]
