# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_dataitem'),
        ('common', '0011_remove_categorypage_description'),
    ]

    operations = [
    ]
