# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_fix_custom_image_sequence'),
        ('common', '0012_merge_20170717_2013'),
    ]

    operations = [
    ]
