# Generated by Django 1.11.3 on 2017-07-18 15:55

from django.db import connection, migrations


def forward(apps, schema_editor):
    CustomImage = apps.get_model("common.CustomImage")
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT * FROM pg_get_serial_sequence(%s, 'id')",
            (CustomImage._meta.db_table,),
        )
        sequence_name = cursor.fetchone()[0]
        cursor.execute(f"SELECT MAX(id) FROM {CustomImage._meta.db_table}")  # nosec
        new_value = cursor.fetchone()[0]
        # This might be a totally new database.
        if new_value:
            cursor.execute(
                f"ALTER SEQUENCE {sequence_name} RESTART WITH %s", (new_value,)
            )  # nosec


def reverse(*args):
    # Intentional no-op.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0013_merge_20170718_1410"),
    ]

    operations = [
        migrations.RunPython(forward, reverse, elidable=True),
    ]
