# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 14:38
from __future__ import unicode_literals

from django.db import migrations


COLORS = CATEGORY_COLOR_CHOICES = [
    'eastern-blue',
    'gamboge',
    'green-apple',
    'green',
    'sunshine',
    'pink',
    'red',
    'royal-blue',
    'teal',
    'violet',
    'yellow',
]


def assign_arbitrary_colors(apps, schema_editor):
    CategoryPage = apps.get_model('common', 'CategoryPage')
    categories = CategoryPage.objects.all().order_by('?')
    for i, page in enumerate(categories):
        page.page_color = CATEGORY_COLOR_CHOICES[i % len(CATEGORY_COLOR_CHOICES)]
        page.save()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_auto_20170719_2347'),
    ]

    operations = [
        migrations.RunPython(assign_arbitrary_colors, noop, elidable=True)
    ]
