# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 15:47
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_auto_20170720_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorypage',
            name='data_table_info',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
    ]
