# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0039_collectionviewrestriction'),
        ('common', '0021_auto_20170720_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='partner_logo_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='partner_logo_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
