# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 15:42
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_add_fields_to_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplepage',
            name='sidebar_content',
            field=wagtail.core.fields.StreamField((('heading', wagtail.core.blocks.StructBlock((('content', wagtail.core.blocks.CharBlock()),))), ('rich_text', wagtail.core.blocks.RichTextBlock())), default=None),
        ),
    ]
