# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-05 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0028_auto_20170802_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationpage',
            name='website',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personpage',
            name='website',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quickfact',
            name='link_url',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
