# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-14 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0029_auto_20180205_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentFieldCategoryPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('incident_field', models.CharField(choices=[('updates', 'updates'), ('categories', 'categories'), ('links', 'links'), ('equipment_seized', 'equipment_seized'), ('equipment_broken', 'equipment_broken'), ('search_image', 'search image'), ('date', 'date'), ('exact_date_unknown', 'exact date unknown'), ('affiliation', 'affiliation'), ('city', 'city'), ('state', 'state'), ('teaser_image', 'teaser image'), ('arrest_status', 'arrest status'), ('status_of_charges', 'status of charges'), ('release_date', 'release date'), ('detention_date', 'detention date'), ('unnecessary_use_of_force', 'unnecessary use of force'), ('lawsuit_name', 'lawsuit name'), ('status_of_seized_equipment', 'status of seized equipment'), ('is_search_warrant_obtained', 'is search warrant obtained'), ('actor', 'actor'), ('border_point', 'border point'), ('stopped_at_border', 'stopped at border'), ('target_us_citizenship_status', 'target us citizenship status'), ('denial_of_entry', 'denial of entry'), ('stopped_previously', 'stopped previously'), ('did_authorities_ask_for_device_access', 'did authorities ask for device access'), ('did_authorities_ask_for_social_media_user', 'did authorities ask for social media user'), ('did_authorities_ask_for_social_media_pass', 'did authorities ask for social media pass'), ('did_authorities_ask_about_work', "Did authorities ask intrusive questions about journalist's work?"), ('were_devices_searched_or_seized', 'were devices searched or seized'), ('assailant', 'assailant'), ('was_journalist_targeted', 'was journalist targeted'), ('charged_under_espionage_act', 'charged under espionage act'), ('subpoena_type', 'subpoena type'), ('subpoena_status', 'subpoena status'), ('held_in_contempt', 'If subject refused to cooperate, were they held in contempt?'), ('detention_status', 'detention status'), ('third_party_in_possession_of_communications', 'third party in possession of communications'), ('third_party_business', 'third party business'), ('legal_order_type', 'legal order type'), ('status_of_prior_restraint', 'status of prior restraint'), ('targets', 'Targets (Journalists/Organizations)'), ('tags', 'Tags'), ('related_incidents', 'related incidents'), ('current_charges', 'Current Charges'), ('dropped_charges', 'Dropped Charges'), ('venue', 'Case Venue'), ('target_nationality', 'Target Nationality'), ('targets_whose_communications_were_obtained', 'Journalists/Organizations whose communications were obtained in leak investigation'), ('politicians_or_public_figures_involved', 'Politicians or public officials involved')], max_length=255)),
                ('category', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_fields', to='common.CategoryPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
