# Generated by Django 1.11.5 on 2018-02-06 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0030_searchsettings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="searchsettings",
            options={"verbose_name": "Incident search"},
        ),
        migrations.AlterField(
            model_name="searchsettings",
            name="search_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="incident.IncidentIndexPage",
            ),
        ),
    ]
