# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-15 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0030_incidentfieldcategorypage'),
        ('common', '0032_auto_20180206_0048'),
    ]

    operations = [
    ]
