# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-15 22:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0035_auto_20180215_2149'),
    ]

    operations = [
        # This migration used to create initial category fields but that got
        # moved to a later migration. This file exists to maintain history.
    ]
