# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0038_auto_20180222_2226'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='incidentfieldcategorypage',
            new_name='categoryincidentfilter',
        ),
        migrations.RenameField(
            model_name='categoryincidentfilter',
            old_name='incident_field',
            new_name='incident_filter',
        ),
        migrations.AlterField(
            model_name='categoryincidentfilter',
            name='incident_filter',
            field=models.CharField(choices=[('were_devices_searched_or_seized', 'Were devices searched or seized?'), ('border_point', 'Border point'), ('target_nationality', 'Target Nationality'), ('held_in_contempt', 'If subject refused to cooperate, were they held in contempt?'), ('actor', 'Actor'), ('politicians_or_public_figures_involved', 'Politicians or public officials involved'), ('status_of_seized_equipment', 'Status of seized equipment'), ('was_journalist_targeted', 'Was journalist targeted?'), ('did_authorities_ask_for_device_access', 'Did authorities ask for device access?'), ('status_of_prior_restraint', 'Status of prior restraint'), ('third_party_in_possession_of_communications', 'Third party in possession of communications'), ('equipment_seized', 'Equipment Seized'), ('did_authorities_ask_for_social_media_pass', 'Did authorities ask for social media password?'), ('dropped_charges', 'Dropped Charges'), ('release_date', 'Release date'), ('denial_of_entry', 'Denied entry?'), ('current_charges', 'Current Charges'), ('charges', None), ('charged_under_espionage_act', 'Charged under espionage act?'), ('did_authorities_ask_about_work', "Did authorities ask intrusive questions about journalist's work?"), ('detention_date', 'Detention date'), ('target_us_citizenship_status', 'US Citizenship Status'), ('legal_order_type', 'Legal order type'), ('arrest_status', 'Arrest status'), ('equipment_broken', 'Equipment Broken'), ('detention_status', 'Detention status'), ('subpoena_type', 'Subpoena type'), ('unnecessary_use_of_force', 'Unnecessary use of force?'), ('is_search_warrant_obtained', 'Search warrant obtained?'), ('stopped_previously', 'Stopped previously?'), ('stopped_at_border', 'Stopped at border?'), ('did_authorities_ask_for_social_media_user', 'Did authorities ask for social media username?'), ('links', 'incident page links'), ('status_of_charges', 'Status of charges'), ('subpoena_status', 'Subpoena status'), ('third_party_business', 'Third party business'), ('targets_whose_communications_were_obtained', 'Journalists/Organizations whose communications were obtained in leak investigation'), ('assailant', 'Assailant')], max_length=255),
        ),
    ]
