# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0040_auto_20180223_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryincidentfilter',
            name='incident_filter',
            field=models.CharField(choices=[('subpoena_type', 'Subpoena type'), ('charged_under_espionage_act', 'Charged under espionage act?'), ('did_authorities_ask_about_work', "Did authorities ask intrusive questions about journalist's work?"), ('was_journalist_targeted', 'Was journalist targeted?'), ('current_charges', 'Current Charges'), ('release_date', 'Release date'), ('status_of_charges', 'Status of charges'), ('actor', 'Actor'), ('third_party_business', 'Third party business'), ('equipment_seized', 'Equipment Seized'), ('equipment_broken', 'Equipment Broken'), ('politicians_or_public_figures_involved', 'Politicians or public officials involved'), ('target_nationality', 'Target Nationality'), ('were_devices_searched_or_seized', 'Were devices searched or seized?'), ('stopped_at_border', 'Stopped at border?'), ('status_of_prior_restraint', 'Status of prior restraint'), ('held_in_contempt', 'If subject refused to cooperate, were they held in contempt?'), ('status_of_seized_equipment', 'Status of seized equipment'), ('target_us_citizenship_status', 'US Citizenship Status'), ('charges', None), ('border_point', 'Border point'), ('subpoena_status', 'Subpoena status'), ('did_authorities_ask_for_social_media_pass', 'Did authorities ask for social media password?'), ('legal_order_type', 'Legal order type'), ('unnecessary_use_of_force', 'Unnecessary use of force?'), ('is_search_warrant_obtained', 'Search warrant obtained?'), ('arrest_status', 'Arrest status'), ('detention_status', 'Detention status'), ('did_authorities_ask_for_social_media_user', 'Did authorities ask for social media username?'), ('did_authorities_ask_for_device_access', 'Did authorities ask for device access?'), ('links', 'incident page links'), ('third_party_in_possession_of_communications', 'Third party in possession of communications'), ('detention_date', 'Detention date'), ('assailant', 'Assailant'), ('denial_of_entry', 'Denied entry?'), ('targets_whose_communications_were_obtained', 'Journalists/Organizations whose communications were obtained in leak investigation'), ('dropped_charges', 'Dropped Charges'), ('stopped_previously', 'Stopped previously?')], max_length=255),
        ),
    ]
