# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-15 22:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0041_auto_20180223_1750'),
        ('home', '0021_auto_20180215_0208'),
        ('forms', '0004_auto_20180215_0208'),
        ('blog', '0015_auto_20180208_0024'),
        ('incident', '0026_auto_20180222_2226'),
        ('menus', '0001_initial'),
        ('emails', '0002_emailsettings'),
        ('wagtailforms', '0001_initial'),
        ('wagtailredirects', '0001_initial'),
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        # Removed runpython migration that relied on particular database state.
    ]
