# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0043_auto_20180228_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryincidentfilter',
            name='incident_filter',
            field=models.CharField(choices=[('equipment_seized', 'Equipment Seized'), ('arrest_status', 'Arrest status'), ('equipment_broken', 'Equipment Broken'), ('did_authorities_ask_about_work', "Did authorities ask intrusive questions about journalist's work?"), ('subpoena_status', 'Subpoena status'), ('target_nationality', 'Target Nationality'), ('denial_of_entry', 'Denied entry?'), ('unnecessary_use_of_force', 'Unnecessary use of force?'), ('stopped_previously', 'Stopped previously?'), ('did_authorities_ask_for_social_media_user', 'Did authorities ask for social media username?'), ('detention_date', 'Detention date'), ('border_point', 'Border point'), ('were_devices_searched_or_seized', 'Were devices searched or seized?'), ('assailant', 'Assailant'), ('targets_whose_communications_were_obtained', 'Journalists/Organizations whose communications were obtained in leak investigation'), ('current_charges', 'Current Charges'), ('charged_under_espionage_act', 'Charged under espionage act?'), ('release_date', 'Release date'), ('detention_status', 'Detention status'), ('is_search_warrant_obtained', 'Search warrant obtained?'), ('held_in_contempt', 'If subject refused to cooperate, were they held in contempt?'), ('third_party_in_possession_of_communications', 'Third party in possession of communications'), ('did_authorities_ask_for_social_media_pass', 'Did authorities ask for social media password?'), ('status_of_charges', 'Status of charges'), ('actor', 'Actor'), ('target_us_citizenship_status', 'US Citizenship Status'), ('stopped_at_border', 'Stopped at border?'), ('subpoena_type', 'Subpoena type'), ('third_party_business', 'Third party business'), ('links', 'incident page links'), ('did_authorities_ask_for_device_access', 'Did authorities ask for device access?'), ('status_of_seized_equipment', 'Status of seized equipment'), ('charges', None), ('was_journalist_targeted', 'Was journalist targeted?'), ('legal_order_type', 'Legal order type'), ('dropped_charges', 'Dropped Charges'), ('status_of_prior_restraint', 'Status of prior restraint'), ('politicians_or_public_figures_involved', 'Politicians or public officials involved')], max_length=255),
        ),
    ]
