# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0044_auto_20180302_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commontag',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='categoryincidentfilter',
            name='incident_filter',
            field=models.CharField(choices=[('target_nationality', 'Target Nationality'), ('arrest_status', 'Arrest status'), ('was_journalist_targeted', 'Was journalist targeted?'), ('status_of_seized_equipment', 'Status of seized equipment'), ('politicians_or_public_figures_involved', 'Politicians or public officials involved'), ('target_us_citizenship_status', 'US Citizenship Status'), ('charged_under_espionage_act', 'Charged under espionage act?'), ('subpoena_status', 'Subpoena status'), ('third_party_business', 'Third party business'), ('border_point', 'Border point'), ('were_devices_searched_or_seized', 'Were devices searched or seized?'), ('did_authorities_ask_for_social_media_user', 'Did authorities ask for social media username?'), ('stopped_at_border', 'Stopped at border?'), ('current_charges', 'Current Charges'), ('equipment_broken', 'Equipment Broken'), ('held_in_contempt', 'If subject refused to cooperate, were they held in contempt?'), ('release_date', 'Release date'), ('charges', None), ('is_search_warrant_obtained', 'Search warrant obtained?'), ('did_authorities_ask_for_social_media_pass', 'Did authorities ask for social media password?'), ('targets_whose_communications_were_obtained', 'Journalists/Organizations whose communications were obtained in leak investigation'), ('did_authorities_ask_about_work', "Did authorities ask intrusive questions about journalist's work?"), ('legal_order_type', 'Legal order type'), ('subpoena_type', 'Subpoena type'), ('actor', 'Actor'), ('unnecessary_use_of_force', 'Unnecessary use of force?'), ('denial_of_entry', 'Denied entry?'), ('status_of_charges', 'Status of charges'), ('detention_status', 'Detention status'), ('did_authorities_ask_for_device_access', 'Did authorities ask for device access?'), ('status_of_prior_restraint', 'Status of prior restraint'), ('stopped_previously', 'Stopped previously?'), ('detention_date', 'Detention date'), ('third_party_in_possession_of_communications', 'Third party in possession of communications'), ('dropped_charges', 'Dropped Charges'), ('equipment_seized', 'Equipment Seized'), ('assailant', 'Assailant'), ('links', 'incident page links')], max_length=255),
        ),
    ]
