# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-14 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0045_auto_20180312_1932'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataItem',
            new_name='StatisticsItem',
        ),
    ]
