# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-15 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0045_auto_20180312_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryincidentfilter',
            name='incident_filter',
            field=models.CharField(choices=[('did_authorities_ask_for_device_access', 'Did authorities ask for device access?'), ('were_devices_searched_or_seized', 'Were devices searched or seized?'), ('links', 'incident page links'), ('equipment_broken', 'Equipment Broken'), ('was_journalist_targeted', 'Was journalist targeted?'), ('politicians_or_public_figures_involved', 'Politicians or public officials involved'), ('detention_date', 'Detention date'), ('status_of_prior_restraint', 'Status of prior restraint'), ('third_party_business', 'Third party business'), ('did_authorities_ask_for_social_media_pass', 'Did authorities ask for social media password?'), ('dropped_charges', 'Dropped Charges'), ('did_authorities_ask_about_work', "Did authorities ask intrusive questions about journalist's work?"), ('charged_under_espionage_act', 'Charged under espionage act?'), ('border_point', 'Border point'), ('third_party_in_possession_of_communications', 'Third party in possession of communications'), ('status_of_charges', 'Status of charges'), ('assailant', 'Assailant'), ('is_search_warrant_obtained', 'Search warrant obtained?'), ('legal_order_type', 'Legal order type'), ('stopped_previously', 'Stopped previously?'), ('unnecessary_use_of_force', 'Unnecessary use of force?'), ('actor', 'Actor'), ('current_charges', 'Current Charges'), ('denial_of_entry', 'Denied entry?'), ('release_date', 'Release date'), ('equipment_seized', 'Equipment Seized'), ('subpoena_status', 'Subpoena status'), ('target_nationality', 'Target Nationality'), ('subpoena_type', 'Subpoena type'), ('target_us_citizenship_status', 'US Citizenship Status'), ('stopped_at_border', 'Stopped at border?'), ('did_authorities_ask_for_social_media_user', 'Did authorities ask for social media username?'), ('arrest_status', 'Arrest status'), ('targets_whose_communications_were_obtained', 'Journalists/Organizations whose communications were obtained in leak investigation'), ('charges', None), ('detention_status', 'Detention status'), ('status_of_seized_equipment', 'Status of seized equipment'), ('held_in_contempt', 'If subject refused to cooperate, were they held in contempt?')], max_length=255),
        ),
        migrations.AlterField(
            model_name='simplepage',
            name='sidebar_content',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.StructBlock((('content', wagtail.wagtailcore.blocks.CharBlock()),))), ('rich_text', wagtail.wagtailcore.blocks.RichTextBlock())), blank=True, default=None, null=True),
        ),
    ]
