# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-14 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0047_auto_20180314_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statisticsitem',
            old_name='data_point',
            new_name='dataset',
        ),
        migrations.AlterField(
            model_name='categoryincidentfilter',
            name='incident_filter',
            field=models.CharField(choices=[('third_party_in_possession_of_communications', 'Third party in possession of communications'), ('stopped_at_border', 'Stopped at border?'), ('third_party_business', 'Third party business'), ('is_search_warrant_obtained', 'Search warrant obtained?'), ('equipment_broken', 'Equipment Broken'), ('target_nationality', 'Target Nationality'), ('release_date', 'Release date'), ('subpoena_status', 'Subpoena status'), ('dropped_charges', 'Dropped Charges'), ('charged_under_espionage_act', 'Charged under espionage act?'), ('unnecessary_use_of_force', 'Unnecessary use of force?'), ('equipment_seized', 'Equipment Seized'), ('current_charges', 'Current Charges'), ('legal_order_type', 'Legal order type'), ('did_authorities_ask_for_device_access', 'Did authorities ask for device access?'), ('were_devices_searched_or_seized', 'Were devices searched or seized?'), ('held_in_contempt', 'If subject refused to cooperate, were they held in contempt?'), ('status_of_prior_restraint', 'Status of prior restraint'), ('charges', None), ('targets_whose_communications_were_obtained', 'Journalists/Organizations whose communications were obtained in leak investigation'), ('status_of_charges', 'Status of charges'), ('did_authorities_ask_for_social_media_pass', 'Did authorities ask for social media password?'), ('target_us_citizenship_status', 'US Citizenship Status'), ('detention_date', 'Detention date'), ('subpoena_type', 'Subpoena type'), ('links', 'incident page links'), ('detention_status', 'Detention status'), ('denial_of_entry', 'Denied entry?'), ('stopped_previously', 'Stopped previously?'), ('arrest_status', 'Arrest status'), ('status_of_seized_equipment', 'Status of seized equipment'), ('was_journalist_targeted', 'Was journalist targeted?'), ('assailant', 'Assailant'), ('border_point', 'Border point'), ('actor', 'Actor'), ('politicians_or_public_figures_involved', 'Politicians or public officials involved'), ('did_authorities_ask_about_work', "Did authorities ask intrusive questions about journalist's work?"), ('did_authorities_ask_for_social_media_user', 'Did authorities ask for social media username?')], max_length=255),
        ),
        migrations.AlterField(
            model_name='statisticsitem',
            name='params',
            field=models.CharField(blank=True, help_text='Whitespace-separated list of arguments to be passed to the statistics function', max_length=255, null=True),
        ),
    ]
