# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-20 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0046_auto_20180315_1513'),
        ('common', '0048_auto_20180314_1810'),
    ]

    operations = [
    ]
