# Generated by Django 2.1.10 on 2019-07-23 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0057_auto_20190723_0332'),
        ('common', '0056_auto_20190528_1539'),
    ]

    operations = [
    ]
