# Generated by Django 2.1.11 on 2019-09-09 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0059_auto_20190723_1851'),
        ('common', '0059_auto_20190806_2055'),
    ]

    operations = [
    ]
