# Generated by Django 2.2.9 on 2020-01-27 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0062_auto_20191023_1738'),
        ('common', '0061_auto_20190909_2046'),
    ]

    operations = [
    ]
