# Generated by Django 2.2.9 on 2020-02-12 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0064_auto_20200127_1832'),
        ('common', '0063_auto_20200203_1915'),
    ]

    operations = [
    ]
