# Generated by Django 2.2.9 on 2020-04-29 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0071_auto_20200408_1938'),
        ('common', '0070_searchsettings_data_download_page'),
    ]

    operations = [
    ]
