# Generated by Django 2.2.12 on 2020-05-18 20:52

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0072_merge_20200429_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='incident_sidebar_note',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.StructBlock([('content', wagtail.blocks.CharBlock())])), ('rich_text', wagtail.blocks.RichTextBlock())], blank=True, default=None, help_text='Note that appears in the sidebar of incident pages, incident index pages, and category pages.', null=True),
        ),
    ]
