# Generated by Django 2.2.12 on 2020-06-03 13:16

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0073_sitesettings_incident_sidebar_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='banner_content',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Banner Content'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_only',
            field=models.BooleanField(default=True, help_text='Boolean for whether to show this sitewide or only on the homepage', verbose_name='Homepage Only'),
        ),
    ]
