# Generated by Django 2.2.24 on 2021-06-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0076_auto_20210127_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='customimage',
            name='slug',
            field=models.CharField(blank=True, help_text='Free-form text. Can be used to store the image filename or other workflow-related information.', max_length=1000, null=True),
        ),
    ]
