# Generated by Django 2.2.24 on 2021-07-21 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0077_customimage_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorypage',
            name='default_image',
            field=models.ForeignKey(blank=True, help_text='Default SEO image for the incidents within this category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.CustomImage'),
        ),
    ]
