# Generated by Django 2.2.26 on 2022-01-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0080_auto_20211208_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorypage',
            name='page_color',
        ),
        migrations.AddField(
            model_name='categorypage',
            name='page_symbol',
            field=models.CharField(choices=[('arrest', 'Arrest Icon'), ('border_stop', 'Border Stop Icon'), ('chilling_statement', 'Chilling Statement Icon'), ('denial_of_access', 'Denial of Access Icon'), ('equipment_damage', 'Equipment Damage Icon'), ('equipment_search', 'Equipment Search Icon'), ('leak_case', 'Leak Case Icon'), ('other_incident', 'Other Incidents Icon'), ('physical_attack', 'Physical Attack Icon'), ('prior_restraint', 'Prior Restraint Icon'), ('subpoena', 'Subpoena Icon')], default='other_incident', help_text='Please check the styleguide to associate the icons with their name', max_length=255),
        ),
    ]
