# Generated by Django 3.2.12 on 2022-03-11 07:40

import common.validators
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0071_alter_incidentpage_introduction'),
        ('blog', '0024_blogpage_introduction'),
        ('common', '0083_alter_simplepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorypage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, validators=[common.validators.TemplateValidator()]),
        ),
        migrations.AlterField(
            model_name='categorypage',
            name='methodology',
            field=wagtail.fields.RichTextField(blank=True, help_text='Detailed description of how we track the data for this particular category.', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='FeaturedCategoryIncident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('category_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_incidents', to='common.categorypage')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='incident.incidentpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeaturedCategoryBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('category_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_blogs', to='common.categorypage')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='blog.blogpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryMethodologyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='methodology_items', to='common.categorypage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
