# Generated by Django 3.2.12 on 2022-03-14 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_blogpage_introduction'),
        ('common', '0085_alter_categorypage_methodology'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorypage',
            name='blog_index_page',
            field=models.ForeignKey(blank=True, help_text='This blog will be linked from the category page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.blogindexpage'),
        ),
    ]
