# Generated by Django 3.2.15 on 2022-10-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0093_auto_20221003_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypage',
            name='viz_data_end',
            field=models.DateField(blank=True, null=True, verbose_name='End Year'),
        ),
        migrations.AlterField(
            model_name='categorypage',
            name='viz_data_start',
            field=models.DateField(blank=True, null=True, verbose_name='Start Year'),
        ),
    ]
