# Generated by Django 3.2.18 on 2023-03-21 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0096_update_verbose_name_of_politician_or_public_figures_relationship'),
        ('common', '0097_auto_20230227_2208'),
    ]

    operations = [
    ]
