# Generated by Django 3.2.20 on 2023-08-22 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0099_create_chart_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartsnapshot',
            name='chart_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.customimage'),
        ),
    ]
