# Generated by Django 3.2.23 on 2023-11-14 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0100_auto_20231106_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_generated', models.DateTimeField(auto_now=True)),
                ('chart_type', models.CharField(choices=[('VERTICAL_BAR', 'Vertical Bar Chart'), ('TREEMAP', 'Treemap'), ('BUBBLE_MAP', 'Bubble Map')], max_length=255)),
                ('query', models.JSONField()),
                ('snapshot_type', models.CharField(choices=[('PNG', 'Raster (PNG)'), ('SVG', 'SVG')], max_length=255)),
                ('chart_svg', models.TextField(null=True)),
                ('chart_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.customimage')),
            ],
        ),
        migrations.AddConstraint(
            model_name='chartsnapshot',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('chart_svg__isnull', False), ('snapshot_type', 'SVG')), models.Q(('chart_image__isnull', False), ('snapshot_type', 'PNG'), models.Q(('chart_image', ''), _negated=True)), _connector='OR'), name='snapshot_type_requires_corresponding_chart'),
        ),
        migrations.AddConstraint(
            model_name='chartsnapshot',
            constraint=models.UniqueConstraint(fields=('query', 'chart_type', 'snapshot_type'), name='unique_types_and_query'),
        ),
    ]
