# Generated by Django 3.2.23 on 2023-11-14 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0102_create_chart_snapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chartsnapshot",
            name="chart_image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.customimage",
            ),
        ),
    ]
