# Generated by Django 4.2.10 on 2024-02-22 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0103_chart_image_to_wagtail_image'),
        ('common', '0104_alter_customimage_file_alter_customrendition_file'),
    ]

    operations = [
    ]
