# Generated by Django 4.2.20 on 2025-08-18 11:50

from django.db import migrations, models

import common.validators


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0110_alter_categoryincidentfilter_incident_filter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commontag",
            name="title",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[common.validators.validate_disallow_comma],
            ),
        ),
    ]
