# Generated by Django 4.2.22 on 2025-10-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0111_alter_commontag_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartsnapshot',
            name='chart_type',
            field=models.CharField(choices=[('VERTICAL_BAR', 'Vertical Bar Chart'), ('TREEMAP', 'Treemap'), ('BUBBLE_MAP', 'Bubble Map'), ('HEXBIN_MAP', 'Hexbin Map')], max_length=255),
        ),
    ]
