# Generated by Django 5.2.14 on 2026-05-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0116_alter_chartsnapshot_last_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorypage',
            name='google_sheets_name',
            field=models.TextField(blank=True, default=None, help_text='Name of this category in the pre-publication Google sheet. Must match the value there exactly.', null=True, unique=True),
        ),
    ]
