# Generated by Django 5.2.15 on 2026-06-25 15:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0118_create_unaccent_search_config"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="footersettings",
            name="partner_logo_link",
        ),
        migrations.RemoveField(
            model_name="footersettings",
            name="partner_logo_text",
        ),
        migrations.DeleteModel(
            name="FooterLogos",
        ),
    ]
