FILTER_CHOICES = [
    ("actor", "Actor"),
    ("workers_whose_communications_were_obtained", "Alleged recipient of leak"),
    ("arrest_status", "Arrest status"),
    ("arresting_authority", "Arresting authority"),
    ("assailant", "Assailant"),
    ("border_point", "Border point"),
    ("case_number", "Case number"),
    ("charged_under_espionage_act", "Charged under Espionage Act?"),
    ("charges", "Charges"),
    ("circuits", "Circuits"),
    ("city", "City"),
    ("denial_of_entry", "Denied entry?"),
    ("detention_date", "Detention date"),
    ("did_authorities_ask_for_device_access", "Did authorities ask for device access?"),
    (
        "did_authorities_ask_about_work",
        "Did authorities ask intrusive questions about journalist's work?",
    ),
    ("equipment_broken", "Equipment broken"),
    ("equipment_seized", "Equipment searched or seized"),
    (
        "politicians_or_public_figures_involved",
        "Government agency or public official involved",
    ),
    ("tags", "Has any of these tags"),
    ("authors", "Incident author"),
    ("links", "Incident page links"),
    ("index_entries", "Index entries"),
    ("legal_order_information_requested", "Information requested in legal order"),
    ("lawsuit_name", "Lawsuit name"),
    ("case_statuses", "Legal case statuses"),
    ("legal_order_status", "Legal order status"),
    ("legal_order_target", "Legal order target"),
    ("legal_order_type", "Legal order type"),
    ("legal_order_venue", "Legal order venue"),
    ("mistakenly_released_materials", "Mistakenly released materials?"),
    ("name_of_business", "Name of business"),
    ("primary_video", "Primary video"),
    ("release_date", "Release date"),
    ("is_search_warrant_obtained", "Search warrant obtained?"),
    ("pending_cases", "Show only pending cases"),
    ("state", "State"),
    ("status_of_charges", "Status of charges"),
    ("status_of_seized_equipment", "Status of equipment"),
    ("status_of_prior_restraint", "Status of prior restraint"),
    ("stopped_previously", "Stopped previously?"),
    ("subpoena_statuses", "Subpoena status"),
    ("subpoena_type", "Subpoena type"),
    ("suppress_footer", "Suppress Footer Call to Action"),
    ("target_nationality", "Target nationality"),
    ("targeted_journalists", "Targeted any of these journalists"),
    ("targeted_institutions", "Targeted institutions"),
    ("third_party_business", "Third party business"),
    ("date", "Took place"),
    ("case_type", "Type of case"),
    ("type_of_denial", "Type of denial"),
    ("target_us_citizenship_status", "US citizenship status"),
    ("unnecessary_use_of_force", "Unnecessary use of force?"),
    ("recently_updated", "Updated in the last"),
    ("venue", "Venue"),
    ("was_journalist_targeted", "Was journalist targeted?"),
]
