#!/usr/bin/env ansible-playbook
---
- name: Provision Dev docker environment
  hosts: localhost
  become: no
  gather_facts: no
  vars:
    # Port to connect to locally, e.g. http://127.0.0.1:8000
    dev_web_port_forward: 8000
  tasks:
    - name: Start postgresql
      docker_container:
        name: postgresql
        image: postgres:9.3
        exposed_ports:
          - 5432
        published_ports:
          - 15432:5432
        volumes:
          - ../../:/django
        state: started
        env:
          POSTGRES_PASSWORD: trackerpassword
          POSTGRES_USER: tracker
          POSTGRES_DB: trackerdb
      register: pg_container_results

    - name: Start node
      docker_container:
        name: node
        image: node:6.10.3-alpine
        volumes:
          - ../../:/var/www/django
        state: started
        working_dir: /var/www/django
        command: /bin/ash -c "apk add paxctl --no-cache; paxctl -cm /usr/local/bin/node; npm install; npm run start"

    - name: Start Django server
      docker_container:
        name: django
        image: quay.io/freedomofpress/ci-python
        volumes:
          - ../../:/var/www/django
        state: started
        working_dir: /var/www/django
        exposed_ports:
          - "{{ dev_web_port_forward }}"
        published_ports:
          - "{{ dev_web_port_forward }}:{{ dev_web_port_forward }}"
        command: |
          /bin/bash -c "pip install -r requirements.txt; ./manage.py migrate; ./manage.py createdevdata; ./manage.py runserver 0.0.0.0:{{ dev_web_port_forward }}"
        env:
          DJANGO_DB_PASSWORD: trackerpassword
          DJANGO_DB_USER: tracker
          DJANGO_DB_NAME: trackerdb
          DJANGO_DB_PORT: 5432
          DJANGO_DB_HOST: "{{ pg_container_results.ansible_facts.docker_container.NetworkSettings.IPAddress }}"

    - name: Display address for local development.
      debug:
        msg: >-
          Development environment spinning-up. You can browse to the web interface at
          http://127.0.0.1:{{ dev_web_port_forward }} once containers finish running.
