# Generated by Django 1.11.1 on 2017-06-28 22:02

from django.db import migrations

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks

import statistics.blocks
import statistics.registry


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.fields.StreamField(
                (
                    (
                        "rich_text",
                        wagtail.blocks.RichTextBlock(
                            icon="doc-full", label="Rich Text"
                        ),
                    ),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                    ("raw_html", wagtail.blocks.RawHTMLBlock()),
                    (
                        "statistics",
                        wagtail.blocks.StructBlock(
                            (
                                (
                                    "visualization",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=statistics.blocks.get_visualization_choices
                                    ),
                                ),
                                (
                                    "dataset",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=statistics.registry.get_stats_choices
                                    ),
                                ),
                                (
                                    "params",
                                    wagtail.blocks.CharBlock(
                                        help_text="Whitespace-separated list of arguments to be passed to the statistics function",
                                        required=False,
                                    ),
                                ),
                            )
                        ),
                    ),
                )
            ),
        ),
    ]
