# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170720_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='link_to_original_post',
            field=models.URLField(blank=True, null=True),
        ),
    ]
