# Generated by Django 1.11.3 on 2017-08-02 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0025_socialsharingseosettings"),
        ("blog", "0009_blogpage_link_to_original_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogindexpage",
            name="search_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="common.CustomImage",
            ),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="search_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="common.CustomImage",
            ),
        ),
    ]
