# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170802_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='about_blog_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
