# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-08 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blogindexpage_feed_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='teaser_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
