# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-08 00:24
from __future__ import unicode_literals

from django.db import migrations
from django.utils.html import strip_tags


def strip_teaser_richtext(apps, schema_editor):
    BlogPage = apps.get_model('blog.BlogPage')
    for page in BlogPage.objects.filter(teaser_text__isnull=False):
        page.teaser_text = strip_tags(page.teaser_text)
        page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20180208_0023'),
    ]

    operations = [
        migrations.RunPython(strip_teaser_richtext, migrations.RunPython.noop, elidable=True),
    ]
