# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-08 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20180205_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='teaser_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
