# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20180208_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='wagtailcore.Page'),
        ),
    ]
