# Generated by Django 3.2.12 on 2022-02-14 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0022_blogindexpagefeature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogindexpagefeature",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blog.blogpage"
            ),
        ),
    ]
