# Generated by Django 3.2.12 on 2022-02-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_blogindexpagefeature_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='introduction',
            field=models.TextField(blank=True, help_text='Optional: introduction displayed above the image/video.', null=True),
        ),
    ]
