# Generated by Django 3.2.15 on 2022-08-16 17:25

from django.db import migrations


def copy_teaserimage_to_leadimage(apps, schema_editor):
    """Copy teaser_image to lead_image for blog pages"""
    BlogPage = apps.get_model('blog', 'BlogPage')

    for blog_page in BlogPage.objects.order_by('pk'):
        blog_page.lead_image = blog_page.teaser_image
        blog_page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20220816_1700'),
    ]

    operations = [
        migrations.RunPython(
            copy_teaserimage_to_leadimage,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
    ]
