# Generated by Django 3.2.19 on 2023-06-29 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_update_and_migrate_incident_set_categories'),
    ]

    operations = [
    ]
