# Generated by Django 4.2.22 on 2025-07-25 11:44

from django.db import migrations


class Migration(migrations.Migration):

    def populate_authors(apps, _):
        BlogPage = apps.get_model("blog", "BlogPage")
        BlogAuthor = apps.get_model("blog", "BlogAuthor")
        for page in BlogPage.objects.all():
            # Ensure both 'author' and 'authors' fields exist
            if page.author:
                print(f"Adding author {page.author.title} to blog {page.id}")
                BlogAuthor.objects.get_or_create(parent_page=page, author=page.author)

    dependencies = [
        ('blog', '0040_blogauthor'),
    ]

    operations = [
         migrations.RunPython(populate_authors, reverse_code=migrations.RunPython.noop),
    ]
