# Generated by Django 4.2.22 on 2025-07-31 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_alter_blogauthor_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='author',
        ),
    ]
