# Generated by Django 4.2.22 on 2025-09-24 17:21

from django.db import migrations

import wagtail.fields

import common.models.helpers
import statistics.registry


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0043_remove_blogpage_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("text", 5),
                    ("aside", 6),
                    ("image", 10),
                    ("raw_html", 11),
                    ("tweet", 13),
                    ("blockquote", 17),
                    ("list", 19),
                    ("video", 22),
                    ("heading_1", 24),
                    ("heading_2", 24),
                    ("heading_3", 24),
                    ("button", 27),
                    ("statistics", 31),
                    ("vertical_bar_chart", 43),
                    ("tree_map_chart", 45),
                    ("bubble_map_chart", 47),
                    ("hexbin_map_chart", 48),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "h2",
                                "h3",
                                "h4",
                                "ol",
                                "ul",
                                "hr",
                                "embed",
                                "link",
                                "document-link",
                                "image",
                                "code",
                            ]
                        },
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("white", "White"),
                                ("eastern-blue", "Eastern Blue"),
                                ("gamboge", "Gamboge"),
                                ("green", "Green"),
                                ("pink", "Pink"),
                                ("red", "Red"),
                                ("royal-blue", "Royal Blue"),
                                ("teal", "Teal"),
                                ("violet", "Violet"),
                                ("dark-gray", "Dark Gray"),
                            ]
                        },
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("right", "Right"),
                            ]
                        },
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("small", "Small"),
                                ("normal", "Normal"),
                                ("large", "Large"),
                                ("jumbo", "Jumbo"),
                            ]
                        },
                    ),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("sans-serif", "Sans Serif"), ("serif", "Serif")]},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 0),
                                ("background_color", 1),
                                ("text_align", 2),
                                ("font_size", 3),
                                ("font_family", 4),
                            ]
                        ],
                        {
                            "label": "Text",
                            "template": "common/blocks/styled_text_full_bleed.html",
                        },
                    ),
                    6: ("wagtail.blocks.StructBlock", [[("text", 0)]], {}),
                    7: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    8: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Image description displayed below the image. Organization/Photographer can be set via the image attribution.",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("right", "Right"),
                                ("full-width", "Full Width"),
                            ]
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 7), ("caption", 8), ("alignment", 9)]],
                        {},
                    ),
                    11: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    12: ("wagtail.embeds.blocks.EmbedBlock", (), {}),
                    13: ("wagtail.blocks.StructBlock", [[("tweet", 12)]], {}),
                    14: ("wagtail.blocks.RichTextBlock", (), {}),
                    15: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    16: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Source text will link to this url.",
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 14), ("source_text", 15), ("source_url", 16)]],
                        {},
                    ),
                    18: ("wagtail.blocks.CharBlock", (), {"label": "List Item"}),
                    19: (
                        "wagtail.blocks.ListBlock",
                        (18,),
                        {"template": "common/blocks/list_block_columns.html"},
                    ),
                    20: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Video description displayed below the video.",
                            "required": False,
                        },
                    ),
                    21: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Organization / Director.",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("video", 12),
                                ("caption", 20),
                                ("attribution", 21),
                                ("alignment", 9),
                            ]
                        ],
                        {},
                    ),
                    23: ("wagtail.blocks.CharBlock", (), {}),
                    24: ("wagtail.blocks.StructBlock", [[("content", 23)]], {}),
                    25: ("wagtail.blocks.TextBlock", (), {"required": True}),
                    26: ("wagtail.blocks.URLBlock", (), {"required": True}),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 25), ("url", 26)]],
                        {},
                    ),
                    28: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": statistics.registry.get_visualization_choices},
                    ),
                    29: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": statistics.registry.get_stats_choices},
                    ),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Whitespace-separated list of arguments to be passed to the statistics function",
                            "required": False,
                        },
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [[("visualization", 28), ("dataset", 29), ("params", 30)]],
                        {},
                    ),
                    32: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    33: (
                        "wagtail.blocks.MultipleChoiceBlock",
                        [],
                        {
                            "choices": common.models.helpers.get_categories,
                            "help_text": "If selected, incidents belonging to any of the selected categories will be included.",
                            "label": "Filter by Category",
                            "required": False,
                        },
                    ),
                    34: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": common.models.helpers.get_tags,
                            "help_text": "If selected, only incidents with the chosen tag will be included.",
                            "label": "Filter by Tag",
                            "required": False,
                        },
                    ),
                    35: (
                        "wagtail.blocks.DateBlock",
                        (),
                        {
                            "help_text": "If set, no incidents before this date will be included.",
                            "label": "Filter by Date, lower bound",
                            "required": False,
                        },
                    ),
                    36: (
                        "wagtail.blocks.DateBlock",
                        (),
                        {
                            "help_text": "If set, no incidents after this date will be included.",
                            "label": "Filter by Date, upper bound",
                            "required": False,
                        },
                    ),
                    37: (
                        "wagtail.blocks.MultipleChoiceBlock",
                        [],
                        {
                            "choices": common.models.helpers.get_states,
                            "help_text": "If selected, only incidents in the chosen states will be included.",
                            "label": "Filter by State",
                            "required": False,
                        },
                    ),
                    38: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("categories", 33),
                                ("tag", 34),
                                ("lower_date", 35),
                                ("upper_date", 36),
                                ("states", 37),
                            ]
                        ],
                        {},
                    ),
                    39: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("months", "Months"), ("years", "Years")],
                            "help_text": "Choose whether to display bars aggregated by months or years. If not provided, will default to months if there is less than two years of data, years if there is more than two years of data.",
                            "label": "Display by",
                            "required": False,
                        },
                    ),
                    40: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": 'Description for assistive technology users. If the chart is demonstrating a specific trend, try to include that, e.g., "Bar chart showing a decreasing number of assaults over the course of 2023."',
                            "required": True,
                        },
                    ),
                    41: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("CATEGORIES", "Categories"),
                                ("ASSAILANT", "Assailant"),
                                ("STATUS_OF_CHARGES", "Status of Charges"),
                            ],
                            "help_text": "If selected, turns this vertical bar chart into a stacked bar chart with incidents grouped by the selected classification.",
                            "label": "Group Incidents By",
                            "required": False,
                        },
                    ),
                    42: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": common.models.helpers.get_tags,
                            "help_text": "If selected, turns this vertical bar chart into a stacked bar chart with incidents grouped by whether or not it has the tag selected. Note that if this field is selected, the group by selection above will be ignored.",
                            "label": "Group Incidents By Tag",
                            "required": False,
                        },
                    ),
                    43: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 32),
                                ("incident_set", 38),
                                ("time_period", 39),
                                ("description", 40),
                                ("group_by", 41),
                                ("group_by_tag", 42),
                            ]
                        ],
                        {},
                    ),
                    44: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("CATEGORIES", "Categories"),
                                ("ASSAILANT", "Assailant"),
                                ("STATUS_OF_CHARGES", "Status of Charges"),
                            ],
                            "label": "Group Incidents By",
                        },
                    ),
                    45: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 32),
                                ("incident_set", 38),
                                ("description", 40),
                                ("group_by", 44),
                            ]
                        ],
                        {},
                    ),
                    46: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("state", "State"), ("city", "City")],
                            "help_text": "Choose whether to group by city or by state",
                            "label": "Group Incidents by",
                        },
                    ),
                    47: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 32),
                                ("incident_set", 38),
                                ("group_by", 46),
                                ("description", 40),
                            ]
                        ],
                        {},
                    ),
                    48: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 32), ("incident_set", 38), ("description", 40)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="lead_graphic",
            field=wagtail.fields.StreamField(
                [
                    ("image", 0),
                    ("vertical_bar_chart", 12),
                    ("tree_map_chart", 14),
                    ("bubble_map_chart", 16),
                    ("hexbin_map_chart", 17),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    1: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    2: (
                        "wagtail.blocks.MultipleChoiceBlock",
                        [],
                        {
                            "choices": common.models.helpers.get_categories,
                            "help_text": "If selected, incidents belonging to any of the selected categories will be included.",
                            "label": "Filter by Category",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": common.models.helpers.get_tags,
                            "help_text": "If selected, only incidents with the chosen tag will be included.",
                            "label": "Filter by Tag",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.DateBlock",
                        (),
                        {
                            "help_text": "If set, no incidents before this date will be included.",
                            "label": "Filter by Date, lower bound",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.DateBlock",
                        (),
                        {
                            "help_text": "If set, no incidents after this date will be included.",
                            "label": "Filter by Date, upper bound",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.MultipleChoiceBlock",
                        [],
                        {
                            "choices": common.models.helpers.get_states,
                            "help_text": "If selected, only incidents in the chosen states will be included.",
                            "label": "Filter by State",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("categories", 2),
                                ("tag", 3),
                                ("lower_date", 4),
                                ("upper_date", 5),
                                ("states", 6),
                            ]
                        ],
                        {},
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("months", "Months"), ("years", "Years")],
                            "help_text": "Choose whether to display bars aggregated by months or years. If not provided, will default to months if there is less than two years of data, years if there is more than two years of data.",
                            "label": "Display by",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": 'Description for assistive technology users. If the chart is demonstrating a specific trend, try to include that, e.g., "Bar chart showing a decreasing number of assaults over the course of 2023."',
                            "required": True,
                        },
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("CATEGORIES", "Categories"),
                                ("ASSAILANT", "Assailant"),
                                ("STATUS_OF_CHARGES", "Status of Charges"),
                            ],
                            "help_text": "If selected, turns this vertical bar chart into a stacked bar chart with incidents grouped by the selected classification.",
                            "label": "Group Incidents By",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": common.models.helpers.get_tags,
                            "help_text": "If selected, turns this vertical bar chart into a stacked bar chart with incidents grouped by whether or not it has the tag selected. Note that if this field is selected, the group by selection above will be ignored.",
                            "label": "Group Incidents By Tag",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 1),
                                ("incident_set", 7),
                                ("time_period", 8),
                                ("description", 9),
                                ("group_by", 10),
                                ("group_by_tag", 11),
                            ]
                        ],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("CATEGORIES", "Categories"),
                                ("ASSAILANT", "Assailant"),
                                ("STATUS_OF_CHARGES", "Status of Charges"),
                            ],
                            "label": "Group Incidents By",
                        },
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 1),
                                ("incident_set", 7),
                                ("description", 9),
                                ("group_by", 13),
                            ]
                        ],
                        {},
                    ),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("state", "State"), ("city", "City")],
                            "help_text": "Choose whether to group by city or by state",
                            "label": "Group Incidents by",
                        },
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 1),
                                ("incident_set", 7),
                                ("group_by", 15),
                                ("description", 9),
                            ]
                        ],
                        {},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("incident_set", 7), ("description", 9)]],
                        {},
                    ),
                },
                default=[],
            ),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="teaser_graphic",
            field=wagtail.fields.StreamField(
                [
                    ("image", 0),
                    ("vertical_bar_chart", 12),
                    ("tree_map_chart", 14),
                    ("bubble_map_chart", 16),
                    ("hexbin_map_chart", 17),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    1: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    2: (
                        "wagtail.blocks.MultipleChoiceBlock",
                        [],
                        {
                            "choices": common.models.helpers.get_categories,
                            "help_text": "If selected, incidents belonging to any of the selected categories will be included.",
                            "label": "Filter by Category",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": common.models.helpers.get_tags,
                            "help_text": "If selected, only incidents with the chosen tag will be included.",
                            "label": "Filter by Tag",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.DateBlock",
                        (),
                        {
                            "help_text": "If set, no incidents before this date will be included.",
                            "label": "Filter by Date, lower bound",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.DateBlock",
                        (),
                        {
                            "help_text": "If set, no incidents after this date will be included.",
                            "label": "Filter by Date, upper bound",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.MultipleChoiceBlock",
                        [],
                        {
                            "choices": common.models.helpers.get_states,
                            "help_text": "If selected, only incidents in the chosen states will be included.",
                            "label": "Filter by State",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("categories", 2),
                                ("tag", 3),
                                ("lower_date", 4),
                                ("upper_date", 5),
                                ("states", 6),
                            ]
                        ],
                        {},
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("months", "Months"), ("years", "Years")],
                            "help_text": "Choose whether to display bars aggregated by months or years. If not provided, will default to months if there is less than two years of data, years if there is more than two years of data.",
                            "label": "Display by",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": 'Description for assistive technology users. If the chart is demonstrating a specific trend, try to include that, e.g., "Bar chart showing a decreasing number of assaults over the course of 2023."',
                            "required": True,
                        },
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("CATEGORIES", "Categories"),
                                ("ASSAILANT", "Assailant"),
                                ("STATUS_OF_CHARGES", "Status of Charges"),
                            ],
                            "help_text": "If selected, turns this vertical bar chart into a stacked bar chart with incidents grouped by the selected classification.",
                            "label": "Group Incidents By",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": common.models.helpers.get_tags,
                            "help_text": "If selected, turns this vertical bar chart into a stacked bar chart with incidents grouped by whether or not it has the tag selected. Note that if this field is selected, the group by selection above will be ignored.",
                            "label": "Group Incidents By Tag",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 1),
                                ("incident_set", 7),
                                ("time_period", 8),
                                ("description", 9),
                                ("group_by", 10),
                                ("group_by_tag", 11),
                            ]
                        ],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("CATEGORIES", "Categories"),
                                ("ASSAILANT", "Assailant"),
                                ("STATUS_OF_CHARGES", "Status of Charges"),
                            ],
                            "label": "Group Incidents By",
                        },
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 1),
                                ("incident_set", 7),
                                ("description", 9),
                                ("group_by", 13),
                            ]
                        ],
                        {},
                    ),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("state", "State"), ("city", "City")],
                            "help_text": "Choose whether to group by city or by state",
                            "label": "Group Incidents by",
                        },
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 1),
                                ("incident_set", 7),
                                ("group_by", 15),
                                ("description", 9),
                            ]
                        ],
                        {},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("incident_set", 7), ("description", 9)]],
                        {},
                    ),
                },
                default=[],
            ),
        ),
    ]
