# Generated by Django 4.2.29 on 2026-04-22 12:42

import common.models.helpers
from django.db import migrations
import statistics.registry
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0046_alter_blogpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogindexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text", 0),
                    ("image", 1),
                    ("raw_html", 2),
                    ("tweet", 4),
                    ("instagram", 6),
                    ("bluesky", 8),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"icon": "doc-full", "label": "Rich Text"},
                    ),
                    1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    2: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    3: ("wagtail.embeds.blocks.EmbedBlock", (), {}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("tweet", 3)]],
                        {"group": "Social Media"},
                    ),
                    5: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {
                            "help_text": "Link to an Instagram post, copied by using the … button and Copy Link."
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("instagram_post", 5)]],
                        {"group": "Social Media"},
                    ),
                    7: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {
                            "help_text": "Link to a Bluesky post, copied by using the Share button and Copy link to post."
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("bluesky_post", 7)]],
                        {"group": "Social Media"},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("text", 5),
                    ("aside", 6),
                    ("image", 12),
                    ("raw_html", 13),
                    ("tweet", 15),
                    ("instagram", 17),
                    ("bluesky", 19),
                    ("blockquote", 22),
                    ("list", 24),
                    ("video", 27),
                    ("heading_1", 29),
                    ("heading_2", 29),
                    ("heading_3", 29),
                    ("button", 32),
                    ("statistics", 36),
                    ("vertical_bar_chart", 48),
                    ("tree_map_chart", 50),
                    ("bubble_map_chart", 52),
                    ("hexbin_map_chart", 53),
                ],
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("white", "White"),
                                ("eastern-blue", "Eastern Blue"),
                                ("gamboge", "Gamboge"),
                                ("green", "Green"),
                                ("pink", "Pink"),
                                ("red", "Red"),
                                ("royal-blue", "Royal Blue"),
                                ("teal", "Teal"),
                                ("violet", "Violet"),
                                ("dark-gray", "Dark Gray"),
                            ]
                        },
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("right", "Right"),
                            ]
                        },
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("small", "Small"),
                                ("normal", "Normal"),
                                ("large", "Large"),
                                ("jumbo", "Jumbo"),
                            ]
                        },
                    ),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("sans-serif", "Sans Serif"), ("serif", "Serif")]},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 0),
                                ("background_color", 1),
                                ("text_align", 2),
                                ("font_size", 3),
                                ("font_family", 4),
                            ]
                        ],
                        {
                            "label": "Text",
                            "template": "common/blocks/styled_text_full_bleed.html",
                        },
                    ),
                    6: ("wagtail.blocks.StructBlock", [[("text", 0)]], {}),
                    7: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    8: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Image description displayed below the image. Organization/Photographer can be set via the image attribution.",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("right", "Right"),
                                ("full-width", "Full Width"),
                            ]
                        },
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "This image may be disturbing. Tap or click to reveal.",
                            "help_text": "Warning text shown on the button above blurred media",
                            "label": "Warning text",
                            "required": True,
                        },
                    ),
                    11: (
                        "wagtail.blocks.ListBlock",
                        (10,),
                        {
                            "default": [],
                            "label": "Add content warning",
                            "max_num": 1,
                            "min_num": 0,
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 7),
                                ("caption", 8),
                                ("alignment", 9),
                                ("content_warning", 11),
                            ]
                        ],
                        {},
                    ),
                    13: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    14: ("wagtail.embeds.blocks.EmbedBlock", (), {}),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("tweet", 14)]],
                        {"group": "Social Media"},
                    ),
                    16: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {
                            "help_text": "Link to an Instagram post, copied by using the … button and Copy Link."
                        },
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("instagram_post", 16)]],
                        {"group": "Social Media"},
                    ),
                    18: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {
                            "help_text": "Link to a Bluesky post, copied by using the Share button and Copy link to post."
                        },
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("bluesky_post", 18)]],
                        {"group": "Social Media"},
                    ),
                    20: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    21: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Source text will link to this url.",
                            "required": False,
                        },
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("source_text", 20), ("source_url", 21)]],
                        {},
                    ),
                    23: ("wagtail.blocks.CharBlock", (), {"label": "List Item"}),
                    24: (
                        "wagtail.blocks.ListBlock",
                        (23,),
                        {"template": "common/blocks/list_block_columns.html"},
                    ),
                    25: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Video description displayed below the video.",
                            "required": False,
                        },
                    ),
                    26: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Organization / Director.",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("video", 14),
                                ("caption", 25),
                                ("attribution", 26),
                                ("alignment", 9),
                            ]
                        ],
                        {},
                    ),
                    28: ("wagtail.blocks.CharBlock", (), {}),
                    29: ("wagtail.blocks.StructBlock", [[("content", 28)]], {}),
                    30: ("wagtail.blocks.TextBlock", (), {"required": True}),
                    31: ("wagtail.blocks.URLBlock", (), {"required": True}),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 30), ("url", 31)]],
                        {},
                    ),
                    33: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": statistics.registry.get_visualization_choices},
                    ),
                    34: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": statistics.registry.get_stats_choices},
                    ),
                    35: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Whitespace-separated list of arguments to be passed to the statistics function",
                            "required": False,
                        },
                    ),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [[("visualization", 33), ("dataset", 34), ("params", 35)]],
                        {},
                    ),
                    37: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    38: (
                        "wagtail.blocks.MultipleChoiceBlock",
                        [],
                        {
                            "choices": common.models.helpers.get_categories,
                            "help_text": "If selected, incidents belonging to any of the selected categories will be included.",
                            "label": "Filter by Category",
                            "required": False,
                        },
                    ),
                    39: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": common.models.helpers.get_tags,
                            "help_text": "If selected, only incidents with the chosen tag will be included.",
                            "label": "Filter by Tag",
                            "required": False,
                        },
                    ),
                    40: (
                        "wagtail.blocks.DateBlock",
                        (),
                        {
                            "help_text": "If set, no incidents before this date will be included.",
                            "label": "Filter by Date, lower bound",
                            "required": False,
                        },
                    ),
                    41: (
                        "wagtail.blocks.DateBlock",
                        (),
                        {
                            "help_text": "If set, no incidents after this date will be included.",
                            "label": "Filter by Date, upper bound",
                            "required": False,
                        },
                    ),
                    42: (
                        "wagtail.blocks.MultipleChoiceBlock",
                        [],
                        {
                            "choices": common.models.helpers.get_states,
                            "help_text": "If selected, only incidents in the chosen states will be included.",
                            "label": "Filter by State",
                            "required": False,
                        },
                    ),
                    43: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("categories", 38),
                                ("tag", 39),
                                ("lower_date", 40),
                                ("upper_date", 41),
                                ("states", 42),
                            ]
                        ],
                        {},
                    ),
                    44: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("months", "Months"), ("years", "Years")],
                            "help_text": "Choose whether to display bars aggregated by months or years. If not provided, will default to months if there is less than two years of data, years if there is more than two years of data.",
                            "label": "Display by",
                            "required": False,
                        },
                    ),
                    45: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": 'Description for assistive technology users. If the chart is demonstrating a specific trend, try to include that, e.g., "Bar chart showing a decreasing number of assaults over the course of 2023."',
                            "required": True,
                        },
                    ),
                    46: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("CATEGORIES", "Categories"),
                                ("ASSAILANT", "Assailant"),
                                ("STATUS_OF_CHARGES", "Status of Charges"),
                            ],
                            "help_text": "If selected, turns this vertical bar chart into a stacked bar chart with incidents grouped by the selected classification.",
                            "label": "Group Incidents By",
                            "required": False,
                        },
                    ),
                    47: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": common.models.helpers.get_tags,
                            "help_text": "If selected, turns this vertical bar chart into a stacked bar chart with incidents grouped by whether or not it has the tag selected. Note that if this field is selected, the group by selection above will be ignored.",
                            "label": "Group Incidents By Tag",
                            "required": False,
                        },
                    ),
                    48: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 37),
                                ("incident_set", 43),
                                ("time_period", 44),
                                ("description", 45),
                                ("group_by", 46),
                                ("group_by_tag", 47),
                            ]
                        ],
                        {"group": "Charts"},
                    ),
                    49: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("CATEGORIES", "Categories"),
                                ("ASSAILANT", "Assailant"),
                                ("STATUS_OF_CHARGES", "Status of Charges"),
                            ],
                            "label": "Group Incidents By",
                        },
                    ),
                    50: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 37),
                                ("incident_set", 43),
                                ("description", 45),
                                ("group_by", 49),
                            ]
                        ],
                        {"group": "Charts"},
                    ),
                    51: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("state", "State"), ("city", "City")],
                            "help_text": "Choose whether to group by city or by state",
                            "label": "Group Incidents by",
                        },
                    ),
                    52: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 37),
                                ("incident_set", 43),
                                ("group_by", 51),
                                ("description", 45),
                            ]
                        ],
                        {"group": "Charts"},
                    ),
                    53: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 37), ("incident_set", 43), ("description", 45)]],
                        {"group": "Charts"},
                    ),
                },
            ),
        ),
    ]
