# Generated by Django 5.2.14 on 2026-06-05 09:31

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0050_alter_blogpage_body_alter_blogpage_lead_graphic_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogindexpage",
            name="newsletter_preamble",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Newsletter preamble that appears at the top of a newsletter before the newsletter image.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="newsletter_preamble",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Overrides the newsletter preamble set in the Blog Index Page for this specific Blog Page.",
                null=True,
                verbose_name="Newsletter preamble override",
            ),
        ),
    ]
