# Generated by Django 5.2.16 on 2026-08-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0051_blogindexpage_newsletter_preamble_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="hide_newsletter_web_link",
            field=models.BooleanField(
                default=False,
                help_text="Check this if the page is never intended to be published.",
                verbose_name="Hide “View this newsletter on pressfreedomtracker.us” banner",
            ),
        ),
    ]
