---
driver:
  name: docker
platforms:
  - name: debian_jessie_pftracker_ci_base
    image: quay.io/freedomofpress/debian-jessie-systemd
    command: /lib/systemd/systemd
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    published_ports:
      - 443
    groups:
      - django
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: buildci
  converge_sequence:
    - destroy
    - create
    - dependency
    - converge
verifier:
  name: testinfra
  lint:
    name: flake8
