# Generated by Django 2.2.12 on 2020-04-13 19:50

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    replaces = [('home', '0001_initial'), ('home', '0002_auto_20170517_1445'), ('home', '0003_auto_20170517_1735'), ('home', '0004_statbox'), ('home', '0005_auto_20170609_2018'), ('home', '0006_homepage_statboxes_label'), ('home', '0007_auto_20170704_1506'), ('home', '0008_change_colors'), ('home', '0009_auto_20170717_2304'), ('home', '0010_auto_20170719_2347'), ('home', '0011_change_statbox_colors'), ('home', '0010_homepage_change_filters_message'), ('home', '0012_merge_20170720_1536'), ('home', '0013_auto_20170720_1539'), ('home', '0014_homepage_search_image'), ('home', '0015_auto_20170804_1543'), ('home', '0016_statbox_external_link'), ('home', '0017_statbox_querystring'), ('home', '0018_auto_20180205_2333'), ('home', '0019_move_all_incidents_to_setting')]

    initial = True

    dependencies = [
        ('common', '0030_searchsettings'),
        ('blog', '0001_initial'),
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
        ('common', '0025_socialsharingseosettings'),
        ('incident', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('about', wagtail.fields.RichTextField(blank=True, help_text='Headings and line breaks will be stripped', null=True)),
                ('about_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
                ('blog_index_page', models.ForeignKey(blank=True, help_text='Recent blog posts will automatically be pulled from this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.BlogIndexPage')),
                ('incident_index_page', models.ForeignKey(blank=True, help_text='Recent incidents will automatically be pulled from this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='incident.IncidentIndexPage')),
                ('statboxes_label', models.CharField(default='Quick Stats', help_text='Title displayed above stat boxes', max_length=255)),
                ('blog_label', models.CharField(default='Partner Articles', help_text='Title displayed above blog posts', max_length=255)),
                ('blog_more_label', models.CharField(default='More Articles', help_text='Text for button to show more blog posts', max_length=255)),
                ('featured_incidents_label', models.CharField(default='Featured Incidents', help_text='Title displayed above featured incidents', max_length=255)),
                ('featured_more_label', models.CharField(default='More Incidents', help_text='Text for button to show more incidents', max_length=255)),
                ('recent_incidents_label', models.CharField(default='Recent Incidents', help_text='Title displayed above recent incidents', max_length=255)),
                ('recent_more_label', models.CharField(default='More Incidents', help_text='Text for button to show more incidents', max_length=255)),
                ('change_filters_message', models.CharField(default='Change filters to search the incident database.', help_text='Text for the filter bar when no filters are applied.', max_length=255)),
                ('search_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.CustomImage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='StatBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('value', models.CharField(max_length=1000)),
                ('label', models.CharField(max_length=1000)),
                ('color', models.CharField(choices=[('eastern-blue', 'Eastern Blue'), ('gamboge', 'Gamboge'), ('green-apple', 'Green Apple'), ('green', 'Green'), ('sunshine', 'Sunshine'), ('pink', 'Pink'), ('red', 'Red'), ('royal-blue', 'Royal Blue'), ('teal', 'Teal'), ('violet', 'Violet'), ('yellow', 'Yellow'), ('dark-gray', 'Dark Gray')], max_length=255)),
                ('internal_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='statboxes', to='home.HomePage')),
                ('external_link', models.URLField(blank=True, default='', help_text='This link will not be used if there is an internal link set.')),
                ('querystring', models.CharField(blank=True, help_text="Append a querystring to the internal link. Should start with '?'", max_length=1000, null=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePageIncidents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='incident.IncidentPage')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='home.HomePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
