# Generated by Django 1.11.1 on 2017-05-17 14:45

import django.db.models.deletion
from django.db import migrations, models

import modelcluster.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0033_remove_golive_expiry_help_text"),
        ("home", "0001_initial"),
        ("incident", "0001_initial"),
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepageincidents",
            name="incident",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="incident.IncidentPage",
            ),
        ),
        migrations.AddField(
            model_name="homepageincidents",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incidents",
                to="home.HomePage",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="about_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.Page",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="blog_index_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="blog.BlogIndexPage",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="incident_index_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="incident.IncidentIndexPage",
            ),
        ),
    ]
