# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 17:35
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170517_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='about',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Headings and line breaks will be stripped', null=True),
        ),
    ]
