# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-24 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='body',
            new_name='about',
        ),
    ]
