# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage_statboxes_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statbox',
            name='color',
            field=models.CharField(choices=[('#119abc', 'Blue'), ('#5b9932', 'Green'), ('#803e79', 'Purple'), ('#dc810b', 'Orange'), ('#2d2e2e', 'Dark Gray'), ('#fff', 'White')], max_length=7),
        ),
    ]
