# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-24 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20170424_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecategories',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.CategoryPage'),
        ),
    ]
