# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-24 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20170424_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='incident_index_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='incident.IncidentIndexPage'),
        ),
    ]
