# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_change_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='blog_label',
            field=models.CharField(default='Partner Articles', help_text='Title displayed above blog posts', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='blog_more_label',
            field=models.CharField(default='More Articles', help_text='Text for button to show more blog posts', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_incidents_label',
            field=models.CharField(default='Featured Incidents', help_text='Title displayed above featured incidents', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_more_label',
            field=models.CharField(default='More Incidents', help_text='Text for button to show more incidents', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='recent_incidents_label',
            field=models.CharField(default='Recent Incidents', help_text='Title displayed above recent incidents', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='recent_more_label',
            field=models.CharField(default='More Incidents', help_text='Text for button to show more incidents', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='blog_index_page',
            field=models.ForeignKey(blank=True, help_text='Recent blog posts will automatically be pulled from this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.BlogIndexPage'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='incident_index_page',
            field=models.ForeignKey(blank=True, help_text='Recent incidents will automatically be pulled from this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='incident.IncidentIndexPage'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='statboxes_label',
            field=models.CharField(default='Quick Stats', help_text='Title displayed above stat boxes', max_length=255),
        ),
    ]
