# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-27 20:19
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_homepageincidents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='about',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
    ]
