# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20170427_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagecategories',
            name='category',
        ),
        migrations.RemoveField(
            model_name='homepagecategories',
            name='page',
        ),
        migrations.DeleteModel(
            name='HomePageCategories',
        ),
    ]
