# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_change_statbox_colors'),
        ('home', '0010_homepage_change_filters_message'),
    ]

    operations = [
    ]
