# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20170804_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='statbox',
            name='external_link',
            field=models.URLField(blank=True, help_text='This link will not be used if there is an internal link set.', null=True),
        ),
    ]
