# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-05 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_statbox_querystring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statbox',
            name='external_link',
            field=models.URLField(blank=True, default='', help_text='This link will not be used if there is an internal link set.'),
            preserve_default=False,
        ),
    ]
