# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-06 00:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_move_all_incidents_to_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='incident_index_page',
        ),
    ]
