# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-06 00:04
from __future__ import unicode_literals

from django.db import migrations

from common.models.settings import SearchSettings
from wagtail.core.models import Site


def move_all_incidents_to_setting(apps, schema_editor):
    HomePage = apps.get_model('home', 'HomePage')
    site = Site.objects.get(is_default_site=True)
    search_settings = SearchSettings.for_site(site)
    try:
        homepage = HomePage.objects.get()
    except HomePage.DoesNotExist:
        pass
    else:
        search_settings.search_page_id = homepage.incident_index_page_id
        search_settings.save()


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20180205_2333'),
        ('common', '0030_searchsettings'),
    ]

    operations = [
        migrations.RunPython(move_all_incidents_to_setting, migrations.RunPython.noop, elidable=True),
    ]
