# Generated by Django 1.11.5 on 2018-02-15 02:08

from django.db import migrations, models

import common.validators


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0020_remove_homepage_incident_index_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statbox",
            name="value",
            field=models.CharField(
                max_length=1000, validators=[common.validators.TemplateValidator()]
            ),
        ),
    ]
