# Generated by Django 2.1.11 on 2019-10-02 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0025_auto_20191002_1616"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepagefeature",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="wagtailcore.Page"
            ),
        ),
    ]
