# Generated by Django 2.2.12 on 2020-04-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20191002_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statbox',
            name='external_link',
            field=models.URLField(blank=True, help_text='This link will not be used if there is an internal link set.'),
        ),
    ]
