# Generated by Django 2.2.12 on 2020-06-24 18:55

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20200413_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statbox',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='statboxes', to='wagtailcore.Page'),
        ),
    ]
