# Generated by Django 3.2.12 on 2022-02-17 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_blogindexpagefeature_page'),
        ('incident', '0069_alter_incidentpage_body'),
        ('home', '0032_featuredblogpost_featuredincident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredblogpost',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='blog.blogpage'),
        ),
        migrations.AlterField(
            model_name='featuredincident',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='incident.incidentpage'),
        ),
    ]
