# Generated by Django 3.2.12 on 2022-03-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20220217_0618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='blog_label',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='blog_more_label',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='change_filters_message',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='content',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featured_more_label',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featured_pages_label',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='recent_more_label',
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_blog_posts_label',
            field=models.CharField(default='From Our Blog', help_text='Title displayed above blog posts', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_blog_posts_more_label',
            field=models.CharField(default='Go to Blog', help_text='Text for button to show more blog posts', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_incidents_label',
            field=models.CharField(default='Featured Incidents', help_text='Title displayed above featured pages', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_incidents_more_label',
            field=models.CharField(default='Go to Incidents Database', help_text='Text for button show more incidents', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='recent_incidents_count',
            field=models.PositiveIntegerField(default=8, help_text='Number of recent incidents to display'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='recent_incidents_more_label',
            field=models.CharField(default='Go to Incidents Database', help_text='Text for button to show more recent incidents', max_length=255),
        ),
    ]
