# Generated by Django 3.2.12 on 2022-03-03 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20220303_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statbox',
            name='internal_link',
        ),
        migrations.RemoveField(
            model_name='statbox',
            name='page',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='statboxes_label',
        ),
        migrations.DeleteModel(
            name='HomePageFeature',
        ),
        migrations.DeleteModel(
            name='StatBox',
        ),
    ]
