# Generated by Django 5.2.16 on 2026-07-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0039_alter_homepage_recent_incidents_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="viz_seven_day_enabled",
            field=models.BooleanField(
                default=False,
                help_text='Show a "past 7 days" option on the homepage charts. It only appears when there are incidents within the last 7 days and becomes the default view when shown.',
                verbose_name="Enable 7-day view",
            ),
        ),
    ]
