# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 22:25
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentpage',
            name='teaser',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='This field is optional and overrides the default teaser text.', null=True, max_length=384),
        ),
    ]
