# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-10 20:45
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('common', '0002_categorypage_tag'),
        ('incident', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='common.Tag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
