# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-11 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0002_incidentpage_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentpage',
            name='org_reported_by',
        ),
    ]
