# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0002_incidentpage_teaser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentpage',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='incidentpage',
            name='detention_date',
            field=models.DateField(blank=True, help_text='This field will default to the date field if not specified.', null=True),
        ),
        migrations.AlterField(
            model_name='incidentpage',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
