# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-11 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('incident', '0003_remove_incidentpage_org_reported_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentPageRelatedLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='incidentpage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_incidents', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='incidentpagerelatedlinks',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_incidents', to='incident.IncidentPage'),
        ),
        migrations.AddField(
            model_name='incidentpagerelatedlinks',
            name='related_incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='wagtailcore.Page'),
        ),
    ]
