# Generated by Django 1.11.1 on 2017-06-26 22:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0004_add_image_caption"),
        ("incident", "0003_incidentpagelinks"),
    ]

    operations = []
