# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import modelcluster.fields


def migrate_targets(apps, schema_editor):
    IncidentPage = apps.get_model('incident', 'IncidentPage')
    Target = apps.get_model('incident', 'Target')
    for page in IncidentPage.objects.all():
        tmp_target_tags = page._tmp_targets.through.objects.all()
        for target_tag in tmp_target_tags:
            target, _ = Target.objects.get_or_create(title=target_tag.tag.name)
            page.targets.add(target)
        page.targets.commit()


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0005_merge_20170626_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='incidentpage',
            old_name='targets',
            new_name='_tmp_targets',
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='targets',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='targets_incidents', to='incident.Target', verbose_name='Targets (Journalists/Organizations)'),
        ),
        migrations.RunPython(migrate_targets),
        migrations.RemoveField(
            model_name='incidentpage',
            name='_tmp_targets'
        ),
        migrations.DeleteModel(name='TargetsTag')
    ]
