# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-11 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0005_incidentpageupdates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentpage',
            name='category',
        ),
    ]
