# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-12 19:28
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0006_remove_incidentpage_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentpagerelatedlinks',
            name='page',
        ),
        migrations.RemoveField(
            model_name='incidentpagerelatedlinks',
            name='related_incident',
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='related_incidents',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='_incidentpage_related_incidents_+', to='incident.IncidentPage'),
        ),
        migrations.DeleteModel(
            name='IncidentPageRelatedLinks',
        ),
    ]
