# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-14 15:25
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20170412_1751'),
        ('incident', '0007_replace_related_incidents'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentpage',
            name='journalists',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='common.PersonPage'),
        ),
    ]
