# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-24 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20170412_1751'),
        ('incident', '0008_incidentindexpage'),
        ('incident', '0009_incidentpage_journalists'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentCategorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('category', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='common.CategoryPage')),
                ('incident_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='incident.IncidentPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
