# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0009_change_tags_to_m2ms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='incidentpage',
            name='jurisdiction',
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='venue',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Courts that are hearing or have heard this case.', related_name='venue_incidents', to='incident.Venue', verbose_name='Case Venue'),
        ),
    ]
