# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-03 01:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('incident', '0010_incidentcategorization'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentpage',
            name='teaser_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
