# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-04 21:04
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
        ('incident', '0011_incidentpage_teaser_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentpage',
            name='journalists',
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='targets',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='targets', to='wagtailcore.Page'),
        ),
    ]
