# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-04 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('incident', '0012_auto_20170504_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargesTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='affiliation',
            field=models.CharField(blank=True, default='Independent', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='is_in_custody',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='status_of_charges',
            field=models.CharField(blank=True, choices=[('', ''), ('UNKNOWN', 'unknown'), ('DETAINED', 'detained and released without being processed'), ('ARRESTED', 'arrested but not charged'), ('PENDING', 'charges pending'), ('DROPPED', 'charges dropped'), ('CONVICTED', 'convicted'), ('ACQUITTED', 'acquitted'), ('APPEAL', 'pending appeal')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='unnecessary_use_of_force',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='incidentpage',
            name='targets',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='targets', to='wagtailcore.Page', verbose_name='Targets (Journalists/Organizations)'),
        ),
        migrations.AddField(
            model_name='chargestag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_charges', to='incident.IncidentPage'),
        ),
        migrations.AddField(
            model_name='chargestag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_chargestag_items', to='taggit.Tag'),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='charges',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='incident.ChargesTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
