# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-05 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('incident', '0013_auto_20170504_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NationalityTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='actor',
            field=models.CharField(blank=True, choices=[('LAW', 'law enforcement'), ('SECURITY', 'private security'), ('CITIZEN', 'private citizen')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='assailant',
            field=models.CharField(blank=True, choices=[('LAW_ENFORCEMENT', 'law enforcement'), ('PRIVATE_SECURITY', 'private security'), ('PRIVATE_INDIVIDUAL', 'private individual')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='border_point',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='charged_under_espionage_act',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='did_authorities_ask_about_work',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='did_authorities_ask_for_device_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='did_authorities_ask_for_device_access_clarify',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='did_authorities_ask_for_social_media',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='did_journalist_give_device',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='did_party_cooperate',
            field=models.CharField(blank=True, choices=[('NOTHING', 'unknown'), ('JUST_TRUE', 'yes'), ('JUST_FALSE', 'false')], max_length=255, null=True, verbose_name='Did journalist or third-party cooperate?'),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='held_in_contempt',
            field=models.CharField(blank=True, choices=[('NOT_HELD', 'not held in contempt'), ('THREATENED', 'threatened with contempt'), ('HELD_NOT_JAILED', 'held in contempt but not jailed'), ('HELD_AND_JAILED', 'held in contempt and jailed')], max_length=255, null=True, verbose_name='If subject refused to cooperate, were they held in contempt?'),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='injury_severity',
            field=models.CharField(blank=True, choices=[('MINOR', 'minor'), ('MODERATE', 'moderate'), ('SERIOUS', 'serious'), ('SEVERE', 'severe'), ('CRITICAL', 'critical'), ('FATAL', 'fatal')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='is_search_warrant_obtained',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='jurisdiction',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Jurisdiction'),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='lawsuit_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='status_of_seized_equipment',
            field=models.CharField(blank=True, choices=[('UNKNOWN', 'unknown'), ('CUSTODY', 'in custody'), ('RETURNED', 'returned'), ('RETURNED_BUT', 'returned but film or SIM cards retained')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='subject_of_prosecution',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='subject_of_subpoena',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='subject_of_subpoena_journalist',
            field=models.CharField(blank=True, choices=[('JOURNALIST', 'journalist'), ('NEWS_ORGANIZATION', 'news organization'), ('TECHNOLOGY', 'technology/communications company'), ('FINANCIAL', 'bank/financial institution'), ('OTHER', 'other')], max_length=255, null=True, verbose_name='Is subject of subpoena a journalist?'),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='subpoena_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'pending'), ('DROPPED', 'dropped'), ('QUASHED', 'quashed'), ('UPHELD', 'upheld'), ('CARRIED_OUT', 'carried out')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='subpoena_type',
            field=models.CharField(blank=True, choices=[('TESTIMONY_ABOUT_SOURCE', 'testimony about confidential source'), ('OTHER_TESTIMONY', 'other testimony'), ('JOURNALIST_COMMUNICATIONS', 'journalist communications or work product')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='target_us_citizenship_status',
            field=models.CharField(blank=True, choices=[('US_CITIZEN', 'U.S. citizen'), ('PERMANENT_RESIDENT', 'permanent resident (green card)'), ('IMMIGRANT_VISA', 'immigrant visa'), ('OTHER_VALID_VISA', 'other valid visa'), ('UNDOCUMENTED', 'undocumented immigrant (including visa overstays)')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='was_assailant_held_accountable',
            field=models.CharField(blank=True, choices=[('NOTHING', 'unknown'), ('JUST_TRUE', 'yes'), ('JUST_FALSE', 'false')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='was_journalist_targeted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='incidentpage',
            name='charges',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='incident.ChargesTag', to='taggit.Tag', verbose_name='Charges'),
        ),
        migrations.AlterField(
            model_name='incidentpage',
            name='status_of_charges',
            field=models.CharField(blank=True, choices=[('UNKNOWN', 'unknown'), ('DETAINED_NO_PROCESSING', 'detained and released without being processed'), ('ARRESTED_NO_CHARGE', 'arrested but not charged'), ('CHARGES_PENDING', 'charges pending'), ('CHARGES_DROPPED', 'charges dropped'), ('CONVICTED', 'convicted'), ('ACQUITTED', 'acquitted'), ('PENDING_APPEAL', 'pending appeal')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nationalitytag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_nationalities', to='incident.IncidentPage'),
        ),
        migrations.AddField(
            model_name='nationalitytag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_nationalitytag_items', to='taggit.Tag'),
        ),
        migrations.AddField(
            model_name='equipmenttag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_equipment', to='incident.IncidentPage'),
        ),
        migrations.AddField(
            model_name='equipmenttag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_equipmenttag_items', to='taggit.Tag'),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='equipment_seized',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='incident.EquipmentTag', to='taggit.Tag', verbose_name='Equipment Seized'),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='target_nationality',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='incident.NationalityTag', to='taggit.Tag', verbose_name='Target Nationality'),
        ),
    ]
