# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0014_incidentpage_display_date_month_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentpage',
            name='display_date_month_only',
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='exact_date_unknown',
            field=models.BooleanField(default=False, help_text='If checked, only the month and year of the incident will be displayed. The date above will be used in filtering by date.'),
        ),
    ]
