# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0015_auto_20170721_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentpagelinks',
            name='publication',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
