# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-08 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0016_equipmenttag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EquipmentBroken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('equipment', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, to='incident.Equipment')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentSeized',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('equipment', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, to='incident.Equipment')),
            ],
        ),
        migrations.RemoveField(
            model_name='equipmenttag',
            name='incident',
        ),
        migrations.AlterField(
            model_name='incidentpage',
            name='did_party_cooperate',
            field=models.CharField(blank=True, choices=[('NOTHING', 'unknown'), ('JUST_TRUE', 'yes'), ('JUST_FALSE', 'no')], max_length=255, null=True, verbose_name='Did journalist or third-party cooperate?'),
        ),
        migrations.AlterField(
            model_name='incidentpage',
            name='was_assailant_held_accountable',
            field=models.CharField(blank=True, choices=[('NOTHING', 'unknown'), ('JUST_TRUE', 'yes'), ('JUST_FALSE', 'no')], max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='EquipmentTag',
        ),
        migrations.AddField(
            model_name='equipmentseized',
            name='incident',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_seized', to='incident.IncidentPage'),
        ),
        migrations.AddField(
            model_name='equipmentbroken',
            name='incident',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_broken', to='incident.IncidentPage'),
        ),
    ]
