# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-08 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0017_auto_20170508_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidentpage',
            old_name='location',
            new_name='address',
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='zip',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentbroken',
            name='equipment',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, to='incident.Equipment', verbose_name='Equipment Broken'),
        ),
        migrations.AlterField(
            model_name='equipmentseized',
            name='equipment',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, to='incident.Equipment', verbose_name='Equipment Seized'),
        ),
    ]
