# Generated by Django 1.11.3 on 2017-08-02 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0025_socialsharingseosettings"),
        ("incident", "0017_incidentpage_search_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="incidentindexpage",
            name="search_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="common.CustomImage",
            ),
        ),
    ]
