# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0018_incidentindexpage_search_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentindexpage',
            name='feed_limit',
            field=models.PositiveIntegerField(default=1000, help_text='Maximum number of incidents to be included in thesyndication feed. 0 for unlimited.'),
        ),
    ]
