# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-06 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0019_incidentindexpage_feed_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentpage',
            name='teaser',
            field=models.TextField(blank=True, help_text='This field is optional and overrides the default teaser text.', max_length=384, null=True),
        ),
    ]
