# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-08 00:24
from __future__ import unicode_literals

from django.db import migrations
from django.utils.html import strip_tags


def strip_teaser_richtext(apps, schema_editor):
    IncidentPage = apps.get_model('incident.IncidentPage')
    for page in IncidentPage.objects.filter(teaser__isnull=False):
        page.teaser = strip_tags(page.teaser)
        page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0020_auto_20180206_0124'),
    ]

    operations = [
        migrations.RunPython(strip_teaser_richtext, migrations.RunPython.noop, elidable=True),
    ]
