# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('incident', '0021_auto_20170510_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentChargesTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DroppedChargesTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PoliticiansOrPublicTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TargetsCommunicationsObtainedTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='chargestag',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='chargestag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='incidentpage',
            name='address',
        ),
        migrations.RemoveField(
            model_name='incidentpage',
            name='charges',
        ),
        migrations.RemoveField(
            model_name='incidentpage',
            name='did_authorities_ask_for_device_access_clarify',
        ),
        migrations.RemoveField(
            model_name='incidentpage',
            name='did_authorities_ask_for_social_media',
        ),
        migrations.RemoveField(
            model_name='incidentpage',
            name='did_journalist_give_device',
        ),
        migrations.RemoveField(
            model_name='incidentpage',
            name='did_party_cooperate',
        ),
        migrations.RemoveField(
            model_name='incidentpage',
            name='injury_severity',
        ),
        migrations.RemoveField(
            model_name='incidentpage',
            name='is_in_custody',
        ),
        migrations.RemoveField(
            model_name='incidentpage',
            name='subject_of_prosecution',
        ),
        migrations.RemoveField(
            model_name='incidentpage',
            name='subject_of_subpoena',
        ),
        migrations.RemoveField(
            model_name='incidentpage',
            name='subject_of_subpoena_journalist',
        ),
        migrations.RemoveField(
            model_name='incidentpage',
            name='was_assailant_held_accountable',
        ),
        migrations.RemoveField(
            model_name='incidentpage',
            name='zip',
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='arrest_status',
            field=models.CharField(blank=True, choices=[('UNKNOWN', 'unknown'), ('DETAINED_NO_PROCESSING', 'detained and released without being processed'), ('DETAINED_CUSTODY', 'detained and still in custody'), ('ARRESTED_CUSTODY', 'arrested and still in custody'), ('ARRESTED_RELEASED', 'arrested and released')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='denial_of_entry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='detention_date',
            field=models.DateTimeField(blank=True, help_text='This field will default to the date field if not specified.', null=True),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='detention_status',
            field=models.CharField(blank=True, choices=[('HELD_IN_CONTEMPT_NO_JAIL', 'held in contempt but not jailed'), ('IN_JAIL', 'in jail'), ('RELEASED', 'released from jail')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='did_authorities_ask_for_social_media_pass',
            field=models.CharField(blank=True, choices=[('NOTHING', 'unknown'), ('JUST_TRUE', 'yes'), ('JUST_FALSE', 'no')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='did_authorities_ask_for_social_media_user',
            field=models.CharField(blank=True, choices=[('NOTHING', 'unknown'), ('JUST_TRUE', 'yes'), ('JUST_FALSE', 'no')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='legal_order_type',
            field=models.CharField(blank=True, choices=[('SUBPOENA', 'subpoena'), ('2703', '2703(d) court order'), ('WARRANT', 'warrant'), ('NATIONAL_SECURITY_LETTER', 'national security letter'), ('FISA', 'FISA order'), ('OTHER', 'other')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='status_of_prior_restraint',
            field=models.CharField(blank=True, choices=[('PENDING', 'pending'), ('DROPPED', 'dropped'), ('STRUCK_DOWN', 'struck down'), ('UPHELD', 'upheld')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='stopped_at_border',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='stopped_previously',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='third_party_business',
            field=models.CharField(blank=True, choices=[('TELECOM', 'telecom company'), ('TECH_COMPANY', 'tech company'), ('ISP', 'internet service provider'), ('FINANCIAL', 'bank/financial institution'), ('TRAVEL', 'travel company'), ('OTHER', 'other')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='third_party_in_possession_of_communications',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='were_devices_searched_or_seized',
            field=models.CharField(blank=True, choices=[('NOTHING', 'unknown'), ('JUST_TRUE', 'yes'), ('JUST_FALSE', 'no')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incidentpage',
            name='actor',
            field=models.CharField(blank=True, choices=[('UNKNOWN', 'unknown'), ('LAW_ENFORCEMENT', 'law enforcement'), ('PRIVATE_SECURITY', 'private security'), ('POLITICIAN', 'politician'), ('PUBLIC_FIGURE', 'public figure'), ('PRIVATE_INDIVIDUAL', 'private individual')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incidentpage',
            name='assailant',
            field=models.CharField(blank=True, choices=[('UNKNOWN', 'unknown'), ('LAW_ENFORCEMENT', 'law enforcement'), ('PRIVATE_SECURITY', 'private security'), ('POLITICIAN', 'politician'), ('PUBLIC_FIGURE', 'public figure'), ('PRIVATE_INDIVIDUAL', 'private individual')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incidentpage',
            name='did_authorities_ask_about_work',
            field=models.CharField(blank=True, choices=[('NOTHING', 'unknown'), ('JUST_TRUE', 'yes'), ('JUST_FALSE', 'no')], max_length=255, null=True, verbose_name="Did authorities ask intrusive questions about journalist's work?"),
        ),
        migrations.AlterField(
            model_name='incidentpage',
            name='did_authorities_ask_for_device_access',
            field=models.CharField(blank=True, choices=[('NOTHING', 'unknown'), ('JUST_TRUE', 'yes'), ('JUST_FALSE', 'no')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incidentpage',
            name='held_in_contempt',
            field=models.CharField(blank=True, choices=[('NOTHING', 'unknown'), ('JUST_TRUE', 'yes'), ('JUST_FALSE', 'no')], max_length=255, null=True, verbose_name='If subject refused to cooperate, were they held in contempt?'),
        ),
        migrations.AlterField(
            model_name='incidentpage',
            name='status_of_charges',
            field=models.CharField(blank=True, choices=[('UNKNOWN', 'unknown'), ('NOT_CHARGED', 'not charged'), ('CHARGES_PENDING', 'charges pending'), ('CHARGES_DROPPED', 'charges dropped'), ('CONVICTED', 'convicted'), ('ACQUITTED', 'acquitted'), ('PENDING_APPEAL', 'pending appeal')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incidentpage',
            name='status_of_seized_equipment',
            field=models.CharField(blank=True, choices=[('UNKNOWN', 'unknown'), ('CUSTODY', 'in custody'), ('RETURNED_FULL', 'returned in full'), ('RETURNED_PART', 'returned in part')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incidentpage',
            name='target_us_citizenship_status',
            field=models.CharField(blank=True, choices=[('US_CITIZEN', 'U.S. citizen'), ('PERMANENT_RESIDENT', 'U.S. permanent resident (green card)'), ('NON_RESIDENT', 'U.S. non-resident')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incidentpage',
            name='was_journalist_targeted',
            field=models.CharField(blank=True, choices=[('NOTHING', 'unknown'), ('JUST_TRUE', 'yes'), ('JUST_FALSE', 'no')], max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='ChargesTag',
        ),
        migrations.AddField(
            model_name='targetscommunicationsobtainedtag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_targets_communications_obtained', to='incident.IncidentPage'),
        ),
        migrations.AddField(
            model_name='targetscommunicationsobtainedtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_targetscommunicationsobtainedtag_items', to='taggit.Tag'),
        ),
        migrations.AddField(
            model_name='politiciansorpublictag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_politicians_or_public', to='incident.IncidentPage'),
        ),
        migrations.AddField(
            model_name='politiciansorpublictag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_politiciansorpublictag_items', to='taggit.Tag'),
        ),
        migrations.AddField(
            model_name='droppedchargestag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_dropped_charges', to='incident.IncidentPage'),
        ),
        migrations.AddField(
            model_name='droppedchargestag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_droppedchargestag_items', to='taggit.Tag'),
        ),
        migrations.AddField(
            model_name='currentchargestag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_current_charges', to='incident.IncidentPage'),
        ),
        migrations.AddField(
            model_name='currentchargestag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_currentchargestag_items', to='taggit.Tag'),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='current_charges',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='incident.CurrentChargesTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='dropped_charges',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='incident.DroppedChargesTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='politicians_or_public_figures_involved',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='incident.PoliticiansOrPublicTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='targets_whose_communications_were_obtained',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='incident.TargetsCommunicationsObtainedTag', to='taggit.Tag', verbose_name='Journalists/Organizations whose communications were obtained in leak investigation'),
        ),
    ]
