# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 01:52
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0022_auto_20170510_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentpage',
            name='current_charges',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='incident.CurrentChargesTag', to='taggit.Tag', verbose_name='Current Changes'),
        ),
        migrations.AlterField(
            model_name='incidentpage',
            name='dropped_charges',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='incident.DroppedChargesTag', to='taggit.Tag', verbose_name='Dropped Changes'),
        ),
        migrations.AlterField(
            model_name='incidentpage',
            name='politicians_or_public_figures_involved',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='incident.PoliticiansOrPublicTag', to='taggit.Tag', verbose_name='Politicians or public officials involved'),
        ),
    ]
