# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0023_auto_20180215_2149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentseized',
            options={'verbose_name': 'Equipment Seized'},
        ),
    ]
