# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0023_auto_20170517_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentpage',
            name='state',
            field=models.CharField(blank=True, help_text='Two character state abbreviation', max_length=2, null=True),
        ),
    ]
