# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0024_auto_20180222_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentbroken',
            options={'verbose_name': 'Equipment Broken'},
        ),
    ]
