# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0028_auto_20180312_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentpagelinks',
            name='url',
            field=models.URLField(max_length=1024),
        ),
    ]
