# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-06 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0029_auto_20180622_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='kind',
            field=models.CharField(blank=True, choices=[('JOURNALIST', 'Journalist'), ('INSTITUTION', 'Institution')], max_length=255, null=True),
        ),
    ]
