# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-13 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0030_target_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentpage',
            name='primary_video',
            field=models.URLField(blank=True, help_text='YouTube or Vimeo URL', null=True),
        ),
    ]
