# Generated by Django 2.1.7 on 2019-04-03 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0031_auto_20190318_2031'),
        ('incident', '0031_auto_20190321_1836'),
    ]

    operations = [
    ]
