# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-19 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0031_auto_20190321_1836'),
        ('incident', '0031_incidentpage_primary_video'),
    ]

    operations = [
    ]
