# Generated by Django 2.1.7 on 2019-07-05 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('incident', '0032_merge_20190403_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentpage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
