# Generated by Django 2.1.7 on 2019-07-23 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0033_auto_20190717_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentpage',
            name='primary_video',
            field=models.URLField(blank=True, help_text='YouTube or Vimeo URL', null=True),
        ),
    ]
