# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-29 16:46
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0033_auto_20190429_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentpage',
            name='targeted_institutions',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='institutions_incidents', to='incident.Institution', verbose_name='Targeted Institutions'),
        ),
    ]
