# Generated by Django 2.1.10 on 2019-08-01 05:44

from django.db import migrations, models


def migrate_suppress_incident_footer(apps, schema_editor):
    IncidentPage = apps.get_model('incident', 'IncidentPage')
    incidents_with_footer = IncidentPage.objects.filter(
        body__contains="catalogues press freedom violations in the United States."
    )
    for incident in incidents_with_footer:
        incident.suppress_footer = True
        incident.save()


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0034_incidentauthor'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentpage',
            name='suppress_footer',
            field=models.BooleanField(default=False, help_text='This field will suppress call to action text. If body already contains cta, can check this field.', verbose_name='Suppress Footer Call to Action'),
        ),
        migrations.RunPython(migrate_suppress_incident_footer, elidable=True),
    ]
