# Generated by Django 1.11.20 on 2019-04-29 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0034_auto_20190429_1646"),
    ]

    operations = [
        migrations.AlterField(
            model_name="targetedjournalist",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="incident.Institution",
            ),
        ),
    ]
