# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-29 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0034_auto_20190429_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetedjournalist',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incident.Institution'),
        ),
    ]
