# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-30 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0035_auto_20190429_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetedjournalist',
            name='journalist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targeted_incidents', to='incident.Journalist'),
        ),
    ]
