# Generated by Django 2.1.7 on 2019-05-28 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0032_merge_20190403_2121'),
        ('incident', '0036_auto_20190430_2022'),
    ]

    operations = [
    ]
