# Generated by Django 2.1.11 on 2019-10-10 09:23

from django.db import migrations


def copy_subpoena_status_to_multi_choice(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    IncidentPage = apps.get_model('incident', 'IncidentPage')
    for incident in IncidentPage.objects.all():
        if incident.subpoena_status:
            incident.subpoena_statuses = [incident.subpoena_status]
            incident.save()


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0037_incidentpage_subpoena_statuses'),
    ]

    operations = [
        migrations.RunPython(copy_subpoena_status_to_multi_choice),
    ]
