# Generated by Django 2.1.10 on 2019-07-23 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0034_incidentauthor'),
        ('incident', '0037_merge_20190528_1459'),
    ]

    operations = [
    ]
