# Generated by Django 2.1.11 on 2019-09-09 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0036_incidentpage_suppress_footer'),
        ('incident', '0038_merge_20190723_1834'),
    ]

    operations = [
    ]
