# Generated by Django 2.2.10 on 2020-03-05 21:28

from django.db import migrations


def copy_affiliation(apps, schema_editor):
    """Copy incident affiliations to """
    IncidentPage = apps.get_model('incident', 'IncidentPage')
    Institution = apps.get_model('incident', 'Institution')

    for incident in IncidentPage.objects.order_by('pk'):
        if incident.affiliation and incident.affiliation != 'Independent':
            inst, _ = Institution.objects.get_or_create(title=incident.affiliation)

            targeted_journos = incident.targeted_journalists.all()
            if targeted_journos:
                for tj in targeted_journos:
                    if not tj.institution:
                        tj.institution = inst
                        tj.save()
            else:
                incident.targeted_institutions.add(inst)
                incident.save()


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0043_auto_20200306_1646'),
    ]

    operations = [
        migrations.RunPython(
            copy_affiliation,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
    ]
