# Generated by Django 2.2.9 on 2020-02-19 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0046_auto_20200306_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentpage',
            name='targets',
        ),
        migrations.RemoveField(
            model_name='incidentpage',
            name='targets_whose_communications_were_obtained',
        ),
        migrations.DeleteModel(
            name='Target',
        ),
    ]
