# Generated by Django 2.2.10 on 2020-02-25 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0047_remove_target_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='governmentworker',
            options={'ordering': ['title'], 'verbose_name': 'Government employee or contractor', 'verbose_name_plural': 'Government employees or contractors'},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='journalist',
            options={'ordering': ['title']},
        ),
    ]
