# Generated by Django 2.2.12 on 2020-04-08 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0048_add_orderings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentpage',
            name='affiliation',
        ),
    ]
