# Generated by Django 2.2.10 on 2020-05-18 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0049_remove_incidentpage_affiliation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentpageupdates',
            name='sort_order',
        ),
    ]
