# Generated by Django 2.2.14 on 2020-09-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0056_auto_20200714_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentpage',
            name='arresting_authority',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Arresting authority'),
        ),
    ]
