# Generated by Django 2.2.19 on 2021-04-15 16:08

from django.db import migrations, models
import incident.models.incident_page


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0059_auto_20201214_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentpage',
            name='subpoena_statuses',
            field=incident.models.incident_page.ChoiceArrayField(base_field=models.CharField(choices=[('UNKNOWN', 'unknown'), ('PENDING', 'pending'), ('DROPPED', 'dropped'), ('QUASHED', 'quashed'), ('UPHELD', 'upheld'), ('CARRIED_OUT', 'carried out'), ('IGNORED', 'ignored')], max_length=255), blank=True, null=True, size=None, verbose_name='Subpoena statuses'),
        ),
    ]
