# Generated by Django 2.2.20 on 2021-04-20 18:35

from django.db import migrations, models


def populate_unique_date(apps, schema_editor):
    """Populate unique_date field for existing incident pages."""
    db_alias = schema_editor.connection.alias
    IncidentPage = apps.get_model('incident', 'IncidentPage')
    for row in IncidentPage.objects.using(db_alias).filter(unique_date__isnull=True):
        row.unique_date = f'{row.date}-{row.pk}'
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0060_auto_20210415_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentpage',
            name='unique_date',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.RunPython(populate_unique_date, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='incidentpage',
            name='unique_date',
            field=models.TextField(unique=True),
        )
    ]
