# Generated by Django 2.2.24 on 2021-06-10 14:26

from django.db import migrations, models
import incident.models.incident_page


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0061_auto_20210420_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentpage',
            name='subpoena_statuses',
            field=incident.models.incident_page.ChoiceArrayField(base_field=models.CharField(choices=[('UNKNOWN', 'unknown'), ('PENDING', 'pending'), ('DROPPED', 'dropped'), ('QUASHED', 'quashed'), ('UPHELD', 'upheld'), ('CARRIED_OUT', 'carried out'), ('IGNORED', 'ignored'), ('OBJECTED_TO', 'objected to')], max_length=255), blank=True, null=True, size=None, verbose_name='Subpoena statuses'),
        ),
    ]
