# Generated by Django 3.2.11 on 2022-02-02 21:57

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0067_incidentpage_case_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentpage',
            name='image_caption',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Image description displayed below the image. Organization/Photographer can be set via the image attribution.', null=True),
        ),
    ]
