# Generated by Django 3.2.11 on 2022-01-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0069_alter_incidentpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentpage',
            name='introduction',
            field=models.TextField(blank=True, help_text='Optional: introduction displayed above the image.'),
        ),
    ]
