# Generated by Django 3.2.11 on 2022-02-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0070_incidentpage_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentpage',
            name='introduction',
            field=models.TextField(blank=True, help_text='Optional: introduction displayed above the image.', null=True),
        ),
    ]
