# Generated by Django 3.2.15 on 2022-08-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0073_convert_to_new_style_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentpage',
            name='arrest_status',
            field=models.CharField(blank=True, choices=[('UNKNOWN', 'unknown'), ('DETAINED_NO_PROCESSING', 'detained and released without being processed'), ('DETAINED_CUSTODY', 'detained and still in custody'), ('ARRESTED_CUSTODY', 'arrested and still in custody'), ('ARRESTED_RELEASED', 'arrested and released'), ('CHARGED_WITHOUT_ARREST', 'charged without arrest')], max_length=255, null=True, verbose_name='Arrest status'),
        ),
    ]
