# Generated by Django 3.2.17 on 2023-02-13 21:56

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0074_update_streamfields_to_use_json_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('SUBPOENA', 'subpoena'), ('2703', '2703(d) court order'), ('WARRANT', 'warrant'), ('MOTION_TO_COMPEL', 'Motion to compel'), ('NATIONAL_SECURITY_LETTER', 'national security letter'), ('FISA', 'FISA order'), ('OTHER', 'other')], max_length=1000)),
                ('information_requested', models.CharField(choices=[('TESTIMONY_ABOUT_SOURCE', 'testimony about confidential source'), ('OTHER_TESTIMONY', 'other testimony'), ('JOURNALIST_COMMUNICATIONS', 'journalist communications or work product'), ('OTHER', 'other')], max_length=1000)),
                ('status', models.CharField(choices=[('UNKNOWN', 'unknown'), ('PENDING', 'pending'), ('DROPPED', 'dropped'), ('QUASHED', 'quashed'), ('UPHELD', 'upheld'), ('CARRIED_OUT', 'carried out'), ('IGNORED', 'ignored'), ('OBJECTED_TO', 'objected to')], max_length=1000)),
                ('date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='incidentpage',
            name='legal_order_target',
            field=models.CharField(blank=True, choices=[('JOURNALIST', 'Journalist'), ('THIRD_PARTY', 'Third Party')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='LegalOrderUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('UNKNOWN', 'unknown'), ('PENDING', 'pending'), ('DROPPED', 'dropped'), ('QUASHED', 'quashed'), ('UPHELD', 'upheld'), ('CARRIED_OUT', 'carried out'), ('IGNORED', 'ignored'), ('OBJECTED_TO', 'objected to')], max_length=1000)),
                ('legal_order', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='incident.legalorder')),
            ],
        ),
        migrations.AddField(
            model_name='legalorder',
            name='incident_page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_orders', to='incident.incidentpage'),
        ),
    ]
