# Generated by Django 3.2.15 on 2022-09-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0074_alter_incidentpage_arrest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargeupdate',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
