# Generated by Django 3.2.18 on 2023-03-20 14:32

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0074_update_streamfields_to_use_json_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentpage',
            name='politicians_or_public_figures_involved',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='politicians_or_public_incidents', to='incident.PoliticianOrPublic', verbose_name='Government agency or public official involved'),
        ),
    ]
