# Generated by Django 3.2.18 on 2023-03-21 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0075_update_verbose_name_of_politician_or_public_figures_relationship'),
        ('incident', '0076_incidentpage_legal_order_venue'),
    ]

    operations = [
    ]
