# Generated by Django 3.2.23 on 2024-01-23 16:08

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0087_alter_incidentpage_type_of_denial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='governmentworker',
            options={'ordering': ['title'], 'verbose_name': 'Alleged Recipient of Leak', 'verbose_name_plural': 'Alleged Recipients of Leaks'},
        ),
        migrations.AlterField(
            model_name='incidentpage',
            name='workers_whose_communications_were_obtained',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='incidents', to='incident.GovernmentWorker', verbose_name='Alleged recipient of leak'),
        ),
    ]
