# Generated by Django 4.2.17 on 2025-01-08 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0090_alter_incidentpage_case_statuses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentpage',
            name='current_charges',
        ),
        migrations.RemoveField(
            model_name='incidentpage',
            name='dropped_charges',
        ),
        migrations.RemoveField(
            model_name='incidentpage',
            name='legal_order_type',
        ),
        migrations.RemoveField(
            model_name='incidentpage',
            name='status_of_charges',
        ),
    ]
