# Generated by Django 4.2.22 on 2025-07-23 19:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0093_alter_equipmentbroken_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="legalorder",
            options={"ordering": ["pk"]},
        ),
    ]
