# Generated by Django 4.2.24 on 2025-09-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0096_add_verdict_issued_status_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentpage',
            name='detention_date',
            field=models.DateField(blank=True, null=True, verbose_name='Detention date'),
        ),
    ]
