# Generated by Django 4.2.28 on 2026-02-13 13:46

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0097_alter_incidentpage_detention_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topicpage",
            name="sidebar",
            field=wagtail.fields.StreamField(
                [
                    ("heading_2", 1),
                    ("rich_text", 2),
                    ("tweet", 4),
                    ("stat_table", 5),
                    ("button", 8),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("wagtail.blocks.StructBlock", [[("content", 0)]], {}),
                    2: (
                        "common.blocks.RichTextTemplateBlock",
                        (),
                        {
                            "editor": "emphasis-with-list",
                            "icon": "doc-full",
                            "label": "Rich Text",
                        },
                    ),
                    3: ("wagtail.embeds.blocks.EmbedBlock", (), {}),
                    4: ("wagtail.blocks.StructBlock", [[("tweet", 3)]], {}),
                    5: ("common.blocks.StatTableBlock", (), {}),
                    6: ("wagtail.blocks.TextBlock", (), {"required": True}),
                    7: ("wagtail.blocks.URLBlock", (), {"required": True}),
                    8: ("wagtail.blocks.StructBlock", [[("text", 6), ("url", 7)]], {}),
                },
            ),
        ),
    ]
