# Generated by Django 4.2.29 on 2026-04-22 12:42

from django.db import migrations

import wagtail.fields

import statistics.registry


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0099_alter_incidentpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incidentpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text", 0),
                    ("image", 1),
                    ("aligned_image", 7),
                    ("raw_html", 8),
                    ("tweet", 10),
                    ("instagram", 12),
                    ("bluesky", 14),
                    ("blockquote", 18),
                    ("pull_quote", 20),
                    ("video", 23),
                    ("statistics", 27),
                ],
                block_lookup={
                    0: (
                        "common.blocks.RichTextTemplateBlock",
                        (),
                        {"icon": "doc-full", "label": "Rich Text"},
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"template": "common/blocks/image_block.html"},
                    ),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Image description displayed below the image. Organization/Photographer can be set via the image attribution.",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("right", "Right"),
                                ("full-width", "Full Width"),
                            ]
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "This image may be disturbing. Tap or click to reveal.",
                            "help_text": "Warning text shown on the button above blurred media",
                            "label": "Warning text",
                            "required": True,
                        },
                    ),
                    6: (
                        "wagtail.blocks.ListBlock",
                        (5,),
                        {
                            "default": [],
                            "label": "Add content warning",
                            "max_num": 1,
                            "min_num": 0,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 2),
                                ("caption", 3),
                                ("alignment", 4),
                                ("content_warning", 6),
                            ]
                        ],
                        {"label": "Aligned, Captioned Image"},
                    ),
                    8: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    9: ("wagtail.embeds.blocks.EmbedBlock", (), {}),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("tweet", 9)]],
                        {"group": "Social Media"},
                    ),
                    11: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {
                            "help_text": "Link to an Instagram post, copied by using the … button and Copy Link."
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("instagram_post", 11)]],
                        {"group": "Social Media"},
                    ),
                    13: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {
                            "help_text": "Link to a Bluesky post, copied by using the Share button and Copy link to post."
                        },
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("bluesky_post", 13)]],
                        {"group": "Social Media"},
                    ),
                    15: ("wagtail.blocks.RichTextBlock", (), {}),
                    16: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    17: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Source text will link to this url.",
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 15), ("source_text", 16), ("source_url", 17)]],
                        {},
                    ),
                    19: ("wagtail.blocks.TextBlock", (), {}),
                    20: ("wagtail.blocks.StructBlock", [[("text", 19)]], {}),
                    21: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Video description displayed below the video.",
                            "required": False,
                        },
                    ),
                    22: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Organization / Director.",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("video", 9),
                                ("caption", 21),
                                ("attribution", 22),
                                ("alignment", 4),
                            ]
                        ],
                        {},
                    ),
                    24: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": statistics.registry.get_visualization_choices},
                    ),
                    25: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": statistics.registry.get_stats_choices},
                    ),
                    26: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Whitespace-separated list of arguments to be passed to the statistics function",
                            "required": False,
                        },
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [[("visualization", 24), ("dataset", 25), ("params", 26)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="incidentpageupdates",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text", 0),
                    ("image", 1),
                    ("raw_html", 2),
                    ("tweet", 4),
                    ("instagram", 6),
                    ("bluesky", 8),
                    ("blockquote", 12),
                    ("video", 16),
                    ("statistics", 20),
                ],
                block_lookup={
                    0: (
                        "common.blocks.RichTextTemplateBlock",
                        (),
                        {"icon": "doc-full", "label": "Rich Text"},
                    ),
                    1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    2: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    3: ("wagtail.embeds.blocks.EmbedBlock", (), {}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("tweet", 3)]],
                        {"group": "Social Media"},
                    ),
                    5: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {
                            "help_text": "Link to an Instagram post, copied by using the … button and Copy Link."
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("instagram_post", 5)]],
                        {"group": "Social Media"},
                    ),
                    7: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {
                            "help_text": "Link to a Bluesky post, copied by using the Share button and Copy link to post."
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("bluesky_post", 7)]],
                        {"group": "Social Media"},
                    ),
                    9: ("wagtail.blocks.RichTextBlock", (), {}),
                    10: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    11: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Source text will link to this url.",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 9), ("source_text", 10), ("source_url", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Video description displayed below the video.",
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Organization / Director.",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("right", "Right"),
                                ("full-width", "Full Width"),
                            ]
                        },
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("video", 3),
                                ("caption", 13),
                                ("attribution", 14),
                                ("alignment", 15),
                            ]
                        ],
                        {},
                    ),
                    17: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": statistics.registry.get_visualization_choices},
                    ),
                    18: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": statistics.registry.get_stats_choices},
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Whitespace-separated list of arguments to be passed to the statistics function",
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("visualization", 17), ("dataset", 18), ("params", 19)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="topicpage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("heading_2", 1),
                    ("raw_html", 2),
                    ("rich_text", 3),
                    ("tweet", 5),
                    ("instagram", 7),
                    ("bluesky", 9),
                    ("tabs", 10),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("wagtail.blocks.StructBlock", [[("content", 0)]], {}),
                    2: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    3: ("wagtail.blocks.RichTextBlock", (), {}),
                    4: ("wagtail.embeds.blocks.EmbedBlock", (), {}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("tweet", 4)]],
                        {"group": "Social Media"},
                    ),
                    6: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {
                            "help_text": "Link to an Instagram post, copied by using the … button and Copy Link."
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("instagram_post", 6)]],
                        {"group": "Social Media"},
                    ),
                    8: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {
                            "help_text": "Link to a Bluesky post, copied by using the Share button and Copy link to post."
                        },
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("bluesky_post", 8)]],
                        {"group": "Social Media"},
                    ),
                    10: ("common.blocks.TabbedBlock", (), {}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="topicpage",
            name="sidebar",
            field=wagtail.fields.StreamField(
                [
                    ("heading_2", 1),
                    ("rich_text", 2),
                    ("tweet", 4),
                    ("instagram", 6),
                    ("bluesky", 8),
                    ("stat_table", 9),
                    ("button", 12),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("wagtail.blocks.StructBlock", [[("content", 0)]], {}),
                    2: (
                        "common.blocks.RichTextTemplateBlock",
                        (),
                        {
                            "editor": "emphasis-with-list",
                            "icon": "doc-full",
                            "label": "Rich Text",
                        },
                    ),
                    3: ("wagtail.embeds.blocks.EmbedBlock", (), {}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("tweet", 3)]],
                        {"group": "Social Media"},
                    ),
                    5: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {
                            "help_text": "Link to an Instagram post, copied by using the … button and Copy Link."
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("instagram_post", 5)]],
                        {"group": "Social Media"},
                    ),
                    7: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {
                            "help_text": "Link to a Bluesky post, copied by using the Share button and Copy link to post."
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("bluesky_post", 7)]],
                        {"group": "Social Media"},
                    ),
                    9: ("common.blocks.StatTableBlock", (), {}),
                    10: ("wagtail.blocks.TextBlock", (), {"required": True}),
                    11: ("wagtail.blocks.URLBlock", (), {"required": True}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 10), ("url", 11)]],
                        {},
                    ),
                },
            ),
        ),
    ]
