# Generated by Django 5.2.13 on 2026-05-09 11:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0116_alter_chartsnapshot_last_generated'),
        ('incident', '0100_add_bluesky_instagram_social_media_embeds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentindexpage',
            name='feed_limit',
            field=models.PositiveIntegerField(default=1000, help_text='Maximum number of incidents to be included in the syndication feed. 0 for unlimited.', null=True),
        ),
        migrations.AlterField(
            model_name='incidentindexpage',
            name='feed_per_page',
            field=models.PositiveIntegerField(default=20, help_text='Maximum number of incidents to be included per page in the syndication feed.', null=True),
        ),
        migrations.AlterField(
            model_name='incidentpage',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='topicpage',
            name='incident_index_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='incident.incidentindexpage'),
        ),
        migrations.AlterField(
            model_name='topicpage',
            name='incident_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='common.commontag'),
        ),
        migrations.AlterField(
            model_name='topicpage',
            name='incidents_per_module',
            field=models.PositiveIntegerField(default=4, help_text='Maximum incidents per category module in category layout', null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(3)]),
        ),
    ]
