# Generated by Django 5.2.14 on 2026-05-21 21:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0102_prepublicationincidentsync_prepublicationincident_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrepublicationSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timespan_length",
                    models.PositiveSmallIntegerField(
                        default=30,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="length",
                    ),
                ),
                (
                    "timespan_units",
                    models.CharField(
                        choices=[
                            ("HOURS", "Hours"),
                            ("DAYS", "Days"),
                            ("WEEKS", "Weeks"),
                            ("MONTHS", "Months"),
                        ],
                        default="DAYS",
                        max_length=20,
                        verbose_name="units",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
