# Generated by Django 5.2.15 on 2026-06-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0103_prepublicationsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prepublicationsettings",
            name="timespan_units",
            field=models.CharField(
                choices=[("DAY", "Days"), ("WEEK", "Weeks"), ("MONTH", "Months")],
                default="DAY",
                max_length=20,
                verbose_name="units",
            ),
        ),
    ]
