# Generated by Django 5.2.15 on 2026-06-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0105_prepublicationsettings_is_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="prepublicationincident",
            name="date_precision",
            field=models.IntegerField(choices=[(1, "Day"), (2, "Month")], default=1),
        ),
    ]
