# Generated by Django 5.2.15 on 2026-07-02 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0106_prepublicationincident_date_precision"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prepublicationincidentsync",
            old_name="message",
            new_name="error_message",
        ),
        migrations.RemoveField(
            model_name="prepublicationincidentsync",
            name="status",
        ),
        migrations.AddField(
            model_name="prepublicationincidentsync",
            name="successful_rows",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name="PrepublicationSyncSkippedRow",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("reason", models.TextField()),
                (
                    "sync",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skipped_rows",
                        to="incident.prepublicationincidentsync",
                    ),
                ),
            ],
        ),
    ]
