# Generated by Django 5.2.16 on 2026-07-27 13:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "incident",
            "0107_rename_message_prepublicationincidentsync_error_message_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incidentpage",
            name="lawsuit_name",
        ),
        migrations.RemoveField(
            model_name="incidentpage",
            name="venue",
        ),
    ]
