# Generated by Django 5.2.17 on 2026-09-30 10:40

from django.db import migrations, models

import common.validators


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0108_remove_incidentpage_lawsuit_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalist",
            name="title",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[common.validators.validate_disallow_AND],
            ),
        ),
    ]
