---
- name: Teardown
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Destroy molecule instance(s)
      docker_container:
        name: "pf_tracker_{{ item }}"
        state: absent
        force_kill: true
      with_items:
        - django
        - node
        - postgresql
