---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: pf_tracker_django
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    side_effect: side_effect.yml
  config_options:
    defaults:
      callback_whitelist: junit
      stdout_callback: unixy
  env:
    JUNIT_OUTPUT_DIR: ../../test-results
scenario:
  name: dev
  converge_sequence:
    - converge
verifier:
  name: testinfra
  directory: ../shared_tests
  options:
    connection: docker
    hosts: pf_tracker_django
  lint:
    name: flake8
