---
- hosts: localhost
  connection: local
  become: no
  vars:
    molecule_scenario_directory: "{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY') }}"
    node_tag: 10.15.1-alpine
    root_dir: "{{ molecule_scenario_directory }}/../../"
  tasks:
    # Trying to avoid `find` b/c not certain about OSX compatibility
    - name: Check for root owned files
      command: find ./ -user root
      args:
        chdir: "{{ root_dir }}"
      ignore_errors: true
      changed_when: false
      register: root_check_result

    - fail:
        msg: |
          Please chown root owned files to continue.
          `make dev-chownroot`
      when:
        - root_check_result.stdout_lines
        - not ansible_kernel.endswith('Microsoft')

    - name: Get hashes from our requirements and dockerfile
      stat:
        path: "{{ item }}"
        get_md5: false
        checksum_algorithm: sha256
      with_items:
        - "../../dev-requirements.txt"
        - "{{ molecule_scenario_directory }}/DjangoDockerfile"
      register: hash_stat_result

    - set_fact:
        requirements_hash: "{{ hash_stat_result.results[0].stat.checksum[0:5] + hash_stat_result.results[1].stat.checksum[0:5]}}"

    - name: Create Django docker image (should be everytime requirements change)
      docker_image:
        name: pf_tracker_django
        dockerfile: "{{ molecule_scenario_directory }}/DjangoDockerfile"
        path: ../../
        tag: "{{ requirements_hash }}"

    - name: Start postgresql
      docker_container:
        name: pf_tracker_postgresql
        image: postgres:9.3
        ports:
          - "127.0.0.1:5432:5432"
        volumes:
          - ../../:/django
        state: started
        env:
          POSTGRES_PASSWORD: trackerpassword
          POSTGRES_USER: tracker
          POSTGRES_DB: trackerdb
        user: postgres
      register: pg_container_results

    - name: Check for existence of grsec kernel
      stat:
        path: /proc/sys/kernel/grsecurity/
      register: check_grsec_kernel_results

    - name: Build node image with pax flags
      docker_image:
        name: "fpf.local/node:{{ node_tag }}"
        dockerfile: "{{ molecule_scenario_directory }}/NodeDockerfile"
        path: ../../
        tag: "{{ node_tag }}"
        buildargs:
          UID: "{{ 1001 if ansible_effective_user_id == 1000 else ansible_effective_user_id }}"

    - name: Purge existing node container wait flag
      file:
        state: absent
        path: "{{ molecule_scenario_directory }}/../../.node_complete"

    - name: Start node
      docker_container:
        name: pf_tracker_node
        image: "fpf.local/node:{{ node_tag }}"
        volumes:
          - ../../:/var/www/django
        state: started
        working_dir: /var/www/django
        command: /bin/ash -c "npm install && touch .node_complete && npm run start"
        user: "{{ 'node1' if ansible_effective_user_id != 1000 else 'node' }}"
        recreate: yes

    - name: Wait for node to finish installing deps
      wait_for:
        path: "{{ molecule_scenario_directory }}/../../.node_complete"

    - name: Establish postgres port
      set_fact:
        pg_port: "{{ lookup('pipe', 'docker port pf_tracker_postgresql 5432').split(':')[1] }}"

    - name: Map Django port to static host port
      set_fact:
        django_port_publish: "8000"
      when: "lookup('env', 'RAND_PORT') | bool"

    - name: Start Django server
      docker_container:
        name: pf_tracker_django
        image: "pf_tracker_django:{{ requirements_hash }}"
        volumes:
          - ../../:/var/www/django
        state: started
        ports:
          - "127.0.0.1:8000:8000"
        working_dir: /var/www/django
        interactive: true
        tty: true
        command: |
          /bin/bash -c "./manage.py migrate; ./manage.py runserver 0.0.0.0:8000"
        env:
          DJANGO_DB_PASSWORD: trackerpassword
          DJANGO_DB_USER: tracker
          DJANGO_DB_NAME: trackerdb
          DJANGO_DB_PORT: 5432
          DJANGO_DB_HOST: "{{ pg_container_results.ansible_facts.docker_container.NetworkSettings.IPAddress }}"
        recreate: yes

    - name: Establish www port
      set_fact:
        www_port: "{{ lookup('pipe', 'docker port pf_tracker_django 8000').split(':')[1] }}"

    - name: Wait for Django runserver to come up
      uri:
        url: "http://localhost:{{ www_port }}"
        method: GET
        status_code: 200
      register: uri_scrape_result
      until: uri_scrape_result.status == 200
      retries: 10
      delay: 20

    - debug:
        msg: |
          Webserver accessible at http://localhost:{{ www_port }}.
          Postgres accessible at localhost:{{ pg_port }}
