---
name: Publish

on:
  push:
    branches: ["develop", "prod"]

permissions:
  contents: read
  actions: read

jobs:
  build-django:
    name: Build:Django
    uses: freedomofpress/actionslib/.github/workflows/oci-build.yaml@main
    permissions:
      contents: read
      actions: read
      packages: write
    with:
      context: "."
      containerfile: devops/docker/ProdDjangoDockerfile
      build-args: |
        USERID=1000
        NPM_VER=9.6.7
      registry: ghcr.io/freedomofpress/pressfreedomtracker-us
      requires-deep-history: true
      add-branch-tags: true

  build-chartgen:
    name: Build:Chartgen
    uses: freedomofpress/actionslib/.github/workflows/oci-build.yaml@main
    permissions:
      contents: read
      actions: read
      packages: write
    with:
      context: '.'
      containerfile: devops/docker/NodeChartPregeneratorDockerfile
      build-args: |
        USERID=1001
        NPM_VER=10.9.2
      registry: ghcr.io/freedomofpress/pressfreedomtracker-us-chartgen
      add-branch-tags: true

